Add direct migration filesystem ownership enhancement
konveyor/enhancements pull request #10
Opened 2021-01-08 19:28 UTC by eriknelson

I wanted to capture our understanding of the filesystem ownership problem and proposed solutions in a more permanent location than a Bugzilla comment, so submitting here for review for posterity.

2021-01-11 21:14 UTC, shawn-hurley requested changes
We have found more edge cases with the destination that we should continue to add to this doc. All the source cluster bits look right to me, though.

2021-01-11 21:14 UTC, shawn-hurley commented on enhancements/direct-migration-filesystem-ownership/README.md
> +  * Attached to one pod, get its fsGroup and use the same fsGroup for the rsync
We should supplemental groups here as well IMO

2021-01-11 21:14 UTC, shawn-hurley commented on enhancements/direct-migration-filesystem-ownership/README.md
> +
There is more here than @alaypatel07 is working on in regards to the destination pod and how to make sure that it is run as none root and keep the same permissions suck that the application pod when migrated will still be able to read/write.

I think we should add that info here as well.

2021-01-11 21:14 UTC, shawn-hurley commented on enhancements/direct-migration-filesystem-ownership/README.md
> +## Edge cases
@alaypatel07 are there potential issues with the destination rysnc server being root with the escape hatch and the application pod having new GIDs/UID

2021-01-14 01:33 UTC, eriknelson commented on enhancements/direct-migration-filesystem-ownership/README.md
> +  * Attached to one pod, get its fsGroup and use the same fsGroup for the rsync
Do we need the selinux context value as well?

2021-01-14 01:40 UTC, eriknelson commented on enhancements/direct-migration-filesystem-ownership/README.md
> +  * Attached to one pod, get its fsGroup and use the same fsGroup for the rsync
Actually, have we audited the rest of the `PodSecurityContext` to determine all of the fields we actually care about? (https://docs.openshift.com/container-platform/4.6/rest_api/objects/index.html#podsecuritycontext-core-v1). I'd expect that we only care about those that will grant us the correct filesystem privileges.

I'm seeing the `SELinuxOptions` option as a struct itself, I'm assuming we would need to clone this full object?

2021-01-14 01:40 UTC, eriknelson commented on enhancements/direct-migration-filesystem-ownership/README.md
> +
@alaypatel07 Can you elaborate on the above?

2021-01-14 16:37 UTC, shawn-hurley commented on enhancements/direct-migration-filesystem-ownership/README.md
> +  indeterminate behavior. Pick any of the pods’s fsGroup at random and use it
nit: s/fsGroup/securityContext/ I think

2021-01-14 16:39 UTC, shawn-hurley approved these changes

2021-01-14 21:02 UTC, merged