Kubernetes provider module for the Konveyor analyzer
konveyor/enhancements pull request #163
Opened 2024-02-07 15:55 UTC by mansam

Fixes https://github.com/konveyor/enhancements/issues/162

2024-02-07 17:30 UTC, shawn-hurley requested changes
I have some questions and some things to think about. 

I think this is on the right track, though!

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +Create a Kubernetes provider for the Konveyor analyzer to perform in-cluster analysis of a live application and its environment. Initially this will include collection and analysis
Analysis of image manifests seems like it maybe should be a separate provider.

I would assume that we would also want to support pulling from registries/searching a repository and other stuff like that. 

I would assume that we would want to pass credentials/proxies and everything for that, while I don't know if the Kubernetes provider. 

For now, I would assume that as a follow on we would solve this use case IMO.

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +## Motivation
Maybe I am an optimist, but is there a desire to scan all applications in all namespaces for the rules?

From the Hub/UI perspective, I understand that it makes sense to focus on the application. Why would we restrict the provider to a single namespace from the CLI or pure analysis engine perspective? Listing across namespaces is trivial so just wondering if we have considered it.

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +* Modification of live resources or automatic enforcement of rules.
+1 as a non-goal

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +### User Stories
Is there a 3rd user, a cluster admin, who wants to search for misbehaving applications in their cluster?

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +In order to perform live cluster analysis, the provider will need to be furnished with cluster credentials
How are we expecting to take credentials?

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +that have read access to the relevant resources. The provider must tolerate limited permissions to the extent possible.
I think we can safely say that we need `list` and `get` on the resources

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +Functionality of the provider itself can be tested with a single-node cluster (seeded with known resources)
Is there any limitation on the current e2e system that would prevent us from creating a new test for this provider?

@djzager

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +```yaml
Is there another example of using the policy?

2024-02-07 17:30 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +The provider will initially surface two rule capabilities: One that is oriented towards ease-of-authorship in exchange for limited expressiveness (`rego.expr`), and one that permits freeform authorin
Why would the provider name be`rego` and not k8s or Kubernetes?

2024-02-07 17:45 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +The provider will initially surface two rule capabilities: One that is oriented towards ease-of-authorship in exchange for limited expressiveness (`rego.expr`), and one that permits freeform authorin
The provider isn't intended to be named rego, but the capability is. Not sure if that makes more sense.

2024-02-07 17:46 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +The provider will initially surface two rule capabilities: One that is oriented towards ease-of-authorship in exchange for limited expressiveness (`rego.expr`), and one that permits freeform authorin
the syntax for the rules is <provider>.<cap> I think that you need to change this to:
kubernetes.rego_module or something similar

2024-02-07 17:53 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +Create a Kubernetes provider for the Konveyor analyzer to perform in-cluster analysis of a live application and its environment. Initially this will include collection and analysis
The reason I think this capability is well suited to this provider is that by gathering resources from the cluster we are already discovering what images are in use and what resources they're associated with. As I understand it, Skopeo does not require doing a full pull of the image in order to inspect it. Credentials are a problem to be solved for sure. I'm not sure to what extent we can derive what we need from what's already pulled into the cluster.

Maybe this will turn out to be way more complicated than I'm anticipating, in which case it may make sense to do it as a separate provider that just happens to share a lot of overlapping implementation details with this one.

2024-02-07 17:56 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +### User Stories
That could be, but I'm not sure if the use case is meaningfully different from the first one in practice even though the motivation is different. I'm definitely open to discussing it further.

2024-02-07 18:03 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +```yaml
What other examples would you like to see?

2024-02-07 19:42 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +Create a Kubernetes provider for the Konveyor analyzer to perform in-cluster analysis of a live application and its environment. Initially this will include collection and analysis
I have a feeling that it will be slightly more complicated, and also usable when not using a Kubernetes cluster, for those reasons I do believe that we should consider moving it out.

With all of this said, I am not opposed to having them share code, but how much is shared in just usage of the library, I personally think it is ok to duplicate some code.

2024-02-07 19:42 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +## Motivation
Yeah we should add this to the enhancement, that way it is apart of any QE test plan and such, especially from the CLI.

2024-02-07 19:44 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +```yaml
Probably one that needs to use the complicated nature of the module; AFAICT, this is just the long version of the shortcut below, or did I miss something?

2024-02-07 19:47 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +In order to perform live cluster analysis, the provider will need to be furnished with cluster credentials
I think that a specific kube config is what I was looking for here; I think it is important because kubeconfig contains not only the user/token but also the coordinates of the cluster API, and we are **not** expecting to take a token or something and create a kubeconfig from the coordinates user/token information.

2024-02-07 20:30 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +Create a Kubernetes provider for the Konveyor analyzer to perform in-cluster analysis of a live application and its environment. Initially this will include collection and analysis
That's fair, image analysis certainly has value outside of a cluster and I wasn't thinking about it that way before.

2024-02-07 20:31 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +```yaml
Yeah, that's the long version of the shortcut for compare/contrast purposes. I'll come up with an additional example that uses the feature more completely.

2024-02-08 14:17 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +The provider will initially surface two rule capabilities: One that is oriented towards ease-of-authorship in exchange for limited expressiveness (`rego.expr`), and one that permits freeform authorin
Now that I think about/see it on the demo, unless we expect to provide other capabilities focused on k8s, I would like to know if k8s-rego.cap is a better name for this provider. 

Unless we can think of things that would be added in the future, I worry about limiting the space in which other providers could work in k8s. if we take the whole provider name here.

2024-02-08 16:07 UTC, eemcmullan commented on enhancements/analyzer-k8s-provider/README.md
> +The Kubernetes provider will use Rego as its rules language, and will use the Open Policy Agent SDK
Could possibly mention the use of analyzer-lsp `providerConfig` and `capability` to evaluate rules/resources.

2024-02-08 16:07 UTC, eemcmullan commented on enhancements/analyzer-k8s-provider/README.md
> +we will provide a built-in inventory of Rego rules that can be referred to by user-provided rules.
@shawn-hurley could this call for a "shim" for rego rules -> our rules? Maybe this isn't worth the trouble if there will only be a limited number of these.

2024-02-28 14:50 UTC, aufi commented on enhancements/analyzer-k8s-provider/README.md
> +that have read access to the relevant resources. The provider must tolerate limited permissions to the extent possible.
I think this part is pretty important for real-world clusters usage. IIRC this was an issue with must-gather in previous migration projects Crane/Forklift when it didn't get `clusteradmin` role, but it created own user&namespace&pod for gathering which we'll not do in this this case, so `list/*`, `get/*` should he hopefully enough.

2024-03-04 18:59 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +The provider will initially surface two rule capabilities: One that is oriented towards ease-of-authorship in exchange for limited expressiveness (`rego.expr`), and one that permits freeform authorin
Renamed to `k8s-resource` for now to better reflect what it does.

2024-03-04 18:59 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +The Kubernetes provider will use Rego as its rules language, and will use the Open Policy Agent SDK
Updated to mention that it will conform to the analyzer-lsp's gRPC provider interface (which would require that).

2024-03-05 19:40 UTC, shawn-hurley approved these changes
For the most part, I think we are good to go, I would personally still like a complex example

2024-03-05 19:40 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +we will provide a built-in inventory of Rego rules that can be referred to by user-provided rules.
I thought that @mansam had by hand moved over the ones that were written. I don't know if there are other larger `rego` projects that we would want to convert. 

I wonder if we have examples of those projects, I think it would make sense, I don't know them and don't know if it needed. Do you have any thoughts?

2024-03-05 19:40 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +Functionality of the provider itself can be tested with a single-node cluster (seeded with known resources)
Is there a world, where we could have a "fake k8s client" that would allow us to run against a set of resources in a directory?

I think that this could be a follow-on especially when we start integrating the rules into the new yaml rule test that @pranavgaikwad is making.

2024-03-05 20:06 UTC, mansam commented on enhancements/analyzer-k8s-provider/README.md
> +Functionality of the provider itself can be tested with a single-node cluster (seeded with known resources)
Yeah, I think we absolutely should look into doing that.

2024-03-06 16:34 UTC, shawn-hurley commented on enhancements/analyzer-k8s-provider/README.md
> +```yaml
This looks great! thank you!

2024-03-06 16:46 UTC, eemcmullan commented on enhancements/analyzer-k8s-provider/README.md
> +we will provide a built-in inventory of Rego rules that can be referred to by user-provided rules.
If it's a small set of rules then I agree, no need. I'm not aware of any others.

2024-03-06 17:43 UTC, pranavgaikwad commented on enhancements/analyzer-k8s-provider/README.md
> +Functionality of the provider itself can be tested with a single-node cluster (seeded with known resources)
@shawn-hurley +100

2024-03-06 20:21 UTC, pranavgaikwad approved these changes

2024-03-07 15:19 UTC, jortel approved these changes
Question:
Is there a use case for analyzing resources not deployed in a cluster.  For example, manifests either user defined or  generated in a git repository?
If so perhaps the provider could honor the `Location` instead of (or in addition) to the kubeconfig and namespaces.
This can be a follow up PR.

2024-03-07 20:30 UTC, djzager approved these changes
ACK

2024-03-08 14:17 UTC, aufi approved these changes

2024-03-14 14:47 UTC, ibragins approved these changes
LGTM

2024-03-20 15:35 UTC, merged