Multi-language support for analysis
konveyor/enhancements pull request #165
Opened 2024-02-14 17:05 UTC by eemcmullan

2024-02-19 16:53 UTC, djzager reviewed
This is a really good start. Thank you for putting this together.

2024-02-19 16:53 UTC, djzager commented on enhancements/multi-language support/README.md
> +- As a user, I want to run analysis on my application that does not have a supported provider.
How do we handle the case where the user wants to run analysis on a Rust and TypeScript application (assume we have TypeScript provider but not Rust)?

2024-02-19 16:53 UTC, djzager commented on enhancements/multi-language support/README.md
> +
I think it's fair to clearly state the idea of reaching out to a provider running somewhere else (via URL endpoint for example) and whether or not Kantra will support that use case or not.

2024-02-22 12:17 UTC, jmle commented on enhancements/multi-language support/README.md
> +
+1

2024-02-22 21:18 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +- As a user, I want to run analysis on my application that does not have a supported provider.
This is a good point, probably an override? I would think a mapping to to "noop" in the user config for that particular language so they don't have to add a `--override-lang <lang>` or something.

2024-02-26 18:37 UTC, shawn-hurley requested changes
An example of the pod that also runs the analyzer container would be helpful, right now, it looks like the pod is only running the provider

2024-02-26 18:37 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +
I think it is fair to state that as a non-goal for this enhancement

2024-02-26 18:37 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +    - "--provider-settings=/opt/settings.json", "--rules=/opt/rulesets/java"
Shouldn't the analyzer-lsp be sending the provider settings in the init config call?

2024-02-26 18:45 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +kind: Pod
@jortel @mansam I think that this should also match what y'all expect the task to run in the hub. I would think that these should match, with potentially different entry points and the hub probably has one more container (the add-on) (IIUC the structure of the hub correctly). 

Let me know what you think

2024-03-01 16:15 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +If a user wishes to run a community provider, or override a supported provider, they must provide a yaml with the container definition. This can be passed in from a new flag such as `--unsupported-pr
I wonder if we start with image and port, with the note that we could eventually need to add support for more stuff because you may need to mount something, or Env Var and maybe even a specific start command?

2024-03-01 18:29 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +These multi-use rulesets can be found in `rulesets/common` and can use labels such as `konveyor.io/provider=go` and `konveyor.io/provider=java` to filter the common rules for relevant providers. For
I think the point is, that they are rules, that are specifically developed to be common and should live in a place where java ruleset author can rely on. If that makes sense?

2024-03-04 18:23 UTC, eemcmullan commented on enhancements/multi-language support/README.md
> +If a user wishes to run a community provider, or override a supported provider, they must provide a yaml with the container definition. This can be passed in from a new flag such as `--unsupported-pr
We can do this and continue to let kantra deal with the volume mounts.

2024-03-04 18:32 UTC, eemcmullan commented on enhancements/multi-language support/README.md
> +We will want to add more default rulesets for each provider, such as `rulesets/golang` and `rulesets/java`. For delivery of these rulesets, they will be packaged in a known location in each providers
I can make this section less definitive then, and add the thought to 'open questions'.

2024-03-04 18:36 UTC, eemcmullan commented on enhancements/multi-language support/README.md
> +These multi-use rulesets can be found in `rulesets/common` and can use labels such as `konveyor.io/provider=go` and `konveyor.io/provider=java` to filter the common rules for relevant providers. For
@pranavgaikwad @shawn-hurley is this something we want to decide here? Or leave it generic for now, and resolve later?

2024-03-04 18:42 UTC, eemcmullan commented on enhancements/multi-language support/README.md
> +- As a user, I want to run analysis on my application that does not have a supported provider.
For this case, I think we would require the user set a provider config for the "unsupported" provider (via a flag) that can be appended to the provider settings we will pass to analyzer-lsp. That will then run in its own container alongside the supported provider container.

2024-03-04 19:35 UTC, mansam commented on enhancements/multi-language support/README.md
> +If a user wishes to run a community provider, or override a supported provider, they must provide a yaml with the container definition. This can be passed in from a new flag such as `--unsupported-pr
If conforming provider images were obligated to accept an environment variable for a port to bind to (something like `ENTRYPOINT provider --port ${PORT}`), then Kantra could just decide a port and further reduce the amount of stuff that needed to be provided by the user.

2024-03-04 19:35 UTC, mansam commented on enhancements/multi-language support/README.md
> +We can then complete our discovery process by grabbing each language `Name` to store in a slice for later use. Further details on how kantra will handle each discovered provider will be discussed bel
Alizer looks like a great way to discover the languages and frameworks that need to be analyzed. How will the discovered languages be mapped to specific providers? (I'm imagining that provider names and language names are not necessarily an exact match, and there could be multiple providers that support a given language).

2024-03-04 19:35 UTC, mansam commented on enhancements/multi-language support/README.md
> +kind: Pod
In the equivalent situation in the hub, the addon container is filling the role of the analyzer-lsp container, and the provider containers are alongside as they are here. I mentioned this below, but I think we should probably establish a convention for the provider's entrypoint and how the port should be provided so that any given provider image is started the same way as any other.

2024-03-04 19:35 UTC, mansam commented on enhancements/multi-language support/README.md
> +We will want to add more default rulesets for each provider. For delivery of these rulesets, they will be packaged in a known location in each providers' Dockerfile. In kantra, this/these path(s) wil
Should the concept of default rules be part of the provider contract? Provider writers could build the default rules into the image and have the provider load them without Kantra or any other caller needing to know where they are in the image. This would help reduce the distinction between supported and community providers since we wouldn't have to do any special-case setup of built-in rules for providers we know about, and built-in rules would automatically work for ones we don't. (We could still have a flag in the init config to turn off the default rules if we felt that was necessary.)

2024-03-05 19:12 UTC, shawn-hurley requested changes
I think we are missing the mapping of the languages to providers as @mansam points out. I think it has to solve a couple of problems
1. It needs to solve the default mapping ("Java" -> Java-provider, "yaml" -> yaml-provider, xml....). 
2. It needs to be overridable
3. It needs to be ok, to turn off a provider for a language, (I have Yaml code but I don't want the yaml provider to be used)
4. It needs to be able to ignore known unknown languages (JavaScript is an example right now).

I think it can be a whole new section

2024-03-05 19:12 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +We can then complete our discovery process by grabbing each language `Name` to store in a slice for later use. Further details on how kantra will handle each discovered provider will be discussed bel
I feel that *we* would need to own a mapping to known built-in providers.

2024-03-05 21:47 UTC, eemcmullan commented on enhancements/multi-language support/README.md
> +If a user wishes to run a community provider, or override a supported provider, they must provide a yaml with the container definition. This can be passed in from a new flag such as `--unsupported-pr
Good point

2024-03-13 18:40 UTC, shawn-hurley commented on enhancements/multi-language support/README.md
> +If a provider mapping is not found, kantra will look for `--unsupported-provider`.
I think that for now this will work, in the future we will want to:
1. Enable this to be some config file for the user to set once and leave it, so they don't have to do this every time
2. Once they do that, enable a "strict" option, that will fail the command if providers are not found.

I think that we can do this as a follow on, but I do worry about the UX of this without those quality of life enhancements.

2024-03-13 18:41 UTC, shawn-hurley approved these changes
I think that we must come back to how to enable folks on the CLI in the future, but this is a huge step forward and I think it is ready to start implementing

2024-03-14 14:45 UTC, ibragins approved these changes
LGTM

2024-03-14 15:20 UTC, istein1 commented
LGTM

2024-03-14 18:25 UTC, merged