:sparkles: Gradle support
konveyor/enhancements pull request #178
Opened 2024-05-10 10:37 UTC by jmle

See https://github.com/konveyor/enhancements/issues/177

2024-05-10 15:52 UTC, rromannissen requested changes
Aside from the overloaded terms, which should be changed, the enhancement looks good to me!

2024-05-10 15:52 UTC, rromannissen commented on enhancements/gradle-support/README.md
> +- The ability to asses the dependencies of Java Gradle projects
_assess_ is an overloaded word with a very specific meaning in the Konveyor domain. I would suggest replacing it with _identify_.

2024-05-10 15:52 UTC, rromannissen commented on enhancements/gradle-support/README.md
> +- As a user, I want to be able to get an assessment of the dependencies used by my Gradle Java project, both direct and transitive.
For the same reasons from my previous comment, I would suggest something like _As a user, I want to be able to identify the dependencies used by my Gradle Java project, both direct and transitive._

2024-05-13 13:52 UTC, aufi approved these changes
Looks good to me. Based on the enhancement text and grade docs, older gradle versions compatibility might be challenging, otherwise looks clear and understandable.

2024-05-13 21:41 UTC, shawn-hurley approved these changes
LGTM, for the most part, I think there are three things that we may want to add or clarify, but in spirit, this is good to go!

2024-05-13 21:41 UTC, shawn-hurley commented on enhancements/gradle-support/README.md
> +Since Konveyor is a Migration & Modernization framework, we should make the enhancement as *backwards compatible as possible*. Projects that use older versions of Gradle are expected.
I think that a table or something that shows the support for versions is going to be necessary. If we don't know now, that is fine, but I did want to call this out and make sure that we doc this.

2024-05-13 21:41 UTC, shawn-hurley commented on enhancements/gradle-support/README.md
> +Some users might work within environments constrained in different forms, usually for security reasons. While the usage of Konveyor within such environments doesn't imply a security risk, the enhance
Does gradle have a settings file or something similar w/ auth/z for contacting a repository of the dependencies. If it does I assume the hub will have to add support.

2024-05-13 21:41 UTC, shawn-hurley commented on enhancements/gradle-support/README.md
> +TBD when targeting release
I think a line here about adding an e2e test, on the hub's go-konveyor-test repo will be worth calling out.

2024-05-15 12:37 UTC, pranavgaikwad approved these changes

2024-05-16 21:33 UTC, cpolizzi commented on enhancements/gradle-support/README.md
> +Since Konveyor is a Migration & Modernization framework, we should make the enhancement as *backwards compatible as possible*. Projects that use older versions of Gradle are expected.
I second this suggestion and also believe it will be necessary to do so.

2024-05-16 21:37 UTC, cpolizzi commented on enhancements/gradle-support/README.md
> +Some users might work within environments constrained in different forms, usually for security reasons. While the usage of Konveyor within such environments doesn't imply a security risk, the enhance
- HTTPS Auth: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:authentication_schemes
- Credential handling: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials

Hope this helps.

2024-05-20 13:45 UTC, jmle commented on enhancements/gradle-support/README.md
> +Since Konveyor is a Migration & Modernization framework, we should make the enhancement as *backwards compatible as possible*. Projects that use older versions of Gradle are expected.
Agreed, we will need to add something like that to the docs.

2024-05-20 13:45 UTC, jmle commented on enhancements/gradle-support/README.md
> +Some users might work within environments constrained in different forms, usually for security reasons. While the usage of Konveyor within such environments doesn't imply a security risk, the enhance
Thanks @cpolizzi

2024-05-20 13:53 UTC, merged