Platform Awareness
konveyor/enhancements pull request #183
Opened 2024-06-12 12:00 UTC by mansam

2024-07-01 10:35 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +An application's deployment environment. For instance, a k8s cluster or
I'm missing Application Servers here: WAS, EAP, Weblogic...

2024-07-01 10:37 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +
I think we should add add a use case around enabling Konveyor to retrieve information about applications directly from the platform in which they are running, like deployment configuration and runtime configuration.

2024-07-01 10:38 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +
Again, I'm missing something about how applications are deployed in the platform.

2024-07-01 10:42 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +
We should also include an application discovery use case: given the coordinates of a given platform, allow the system to discover the applications deployed on it and populate the inventory accordingly.

2024-07-01 10:43 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +environment but not in source control or other documentation. Combining
Application configuration is a must as well, especially if we intend to tackle assets generation.

2024-07-01 10:44 UTC, rromannissen commented on enhancements/platform-awareness/README.md
> +
The hub should be able to retrieve deployment and runtime information about applications and store it in canonical form, for it to be used to output potential assets in subsequent stages of the migration process.

2024-07-01 10:49 UTC, rromannissen requested changes
I think this is a good start for the k8s side of platform awareness an the integration with tools such as Crane, but it's completely missing everything related to application deployment and runtime configuration.

2025-05-04 11:08 UTC, istein1 commented
Closing this PR as we have https://github.com/konveyor/enhancements/pull/210 that supersedes it.

2025-05-04 11:08 UTC, closed without merging