:sparkles: Add kantra multiple inputs enhancement
konveyor/enhancements pull request #198
Opened 2024-08-14 08:46 UTC by aufi

Adding multiple inputs support for kantra analyze command.

Fixes: https://github.com/konveyor/enhancements/issues/194

2024-08-14 11:52 UTC, shawn-hurley requested changes
I thnk that we need a little more info in the Design section to fully capture what we plan on doing. 

We also need to make sure that any of these changes is added to the this are incorporated in the enhancement from @eemcmullan. Can you two work together to make sure that happens?

2024-08-14 11:52 UTC, shawn-hurley commented on enhancements/kantra/multiple-inputs/README.md
> +Users community requested add support for multiple inputs to kantra, that would match to previous _mta-cli_ tool multiple inputs feature. In order to accomplish that, kantra will be updated to accept
nit: wording, I think something more like `We want to to add support...` or something more like that?

2024-08-14 11:52 UTC, shawn-hurley commented on enhancements/kantra/multiple-inputs/README.md
> +This enhancement should close a feature gap to "original" mta-cli multiple input option and increase usability of kantra tool.
I wonder if we can by pass the feature parity argument and get to the motivation of the need for multiple inputs. Something like 

`Users have a large portfolio of applications, and running kantra on these individually is a time consuming process that leads them to have multiple different static reports. Having a single static report for all the local applications they are working on will greatly increase the visability of known issues across the local portfolio` 

Or something like that?

2024-08-14 11:52 UTC, shawn-hurley commented on enhancements/kantra/multiple-inputs/README.md
> +It would be nice to generate static-report after each input application analysis completion to have some static-report available before finishing all inputs or for a case that analysis crash or an un
are we planning on looping over each input? what happens if the analysis command fails for B while running ABC. I think writing out the error scenarios here would be helpful.

2024-08-14 13:43 UTC, aufi commented on enhancements/kantra/multiple-inputs/README.md
> +It would be nice to generate static-report after each input application analysis completion to have some static-report available before finishing all inputs or for a case that analysis crash or an un
Good point, will update.

2024-08-15 13:35 UTC, eemcmullan commented on enhancements/kantra/multiple-inputs/README.md
> +It would be nice to generate static-report after each input application analysis completion to have some static-report available before finishing all inputs or for a case that analysis crash or an un
One thing that may be good to discuss is how the providers will be handled. Will we create new provider containers for every input? Or check to see which are already running? That may get tricky with the shared volume, which is the input dir, and the shared network.

2024-08-15 13:35 UTC, eemcmullan commented on enhancements/kantra/multiple-inputs/README.md
> +All analysis options are the same for all input applications and there is no plan to implement different source/targets/... for different input applications.
Definitely something to document

2024-08-16 13:02 UTC, aufi commented on enhancements/kantra/multiple-inputs/README.md
> +It would be nice to generate static-report after each input application analysis completion to have some static-report available before finishing all inputs or for a case that analysis crash or an un
I was thinking about adding something like that the performance is not the main focus of this multiple inputs feature, so it might be OK re-create needed containers/networks etc. to not overcomplicate the codebase. But I'm not sure if this is the right approach.

2024-09-04 13:47 UTC, eemcmullan approved these changes

2024-09-12 14:09 UTC, shawn-hurley approved these changes

2024-09-13 08:47 UTC, merged