add crane-2.0 discovery enhancement
konveyor/enhancements pull request #22
Opened 2021-05-04 02:42 UTC by alaypatel07

2021-05-04 20:02 UTC, shawn-hurley requested changes
Some suggestions and some questions. Good start though IMO

2021-05-04 20:02 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> + |  |   |- failed-kind.yaml
this is failed kind because the list request failed right?

Should we add failed-kind-list or something to make that clear at a glance?

2021-05-04 20:02 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> + skip "virtual resources" (resources that do not support "create" verb).
Do we also skip resources that do not have a list verb?

2021-05-06 16:31 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> +- be used by the namespace admin (not cluster-admin)
+1 makes sense, that captures it better I think

2021-05-06 16:33 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> +- This tool will not be intended for a cluster admin, hence it will not backup
well I was not clear what plans we have right now to handle cluster configuration, can we simply state here that cluster configuration is not the goal of this tool, we will create a separate enhancement that handles this case in the future (whenever we get to it). WDYT?

2021-05-06 16:33 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + |  |   |- kind-a_namespace-2_name-1.yaml
+1

2021-05-06 16:42 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + |  |   |- failed-kind.yaml
>  this is failed kind because the list request failed right?

Yes but Im wonderng if that technical detail needed? I am not 100% sure if "foo-list.yaml" will be interpreted as "foo failed because of list method" or "list of all the foo kind resources that failed"

But I like the idea of providing "at a glance information of what failed"

2021-05-06 16:42 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + skip "virtual resources" (resources that do not support "create" verb).
+1

2021-05-06 18:31 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> +- be used by the namespace admin (not cluster-admin)
Updated @shawn-hurley PTAL

2021-05-06 18:32 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> +- will create a YAML dump of all the namespaced resources
refined the language here PTAL

2021-05-06 18:32 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + |  |   |- kind-a_namespace-2_name-1.yaml
removed

2021-05-06 18:33 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + skip "virtual resources" (resources that do not support "create" verb).
updated

2021-05-06 21:54 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> +- This tool will not be intended for a cluster admin, hence it will not backup
Yeag agree

2021-05-06 21:59 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> + |  |   |- failed-kind.yaml
Yes, I see, the difference, is it obvious when you look at the file that it was the list method?

2021-05-06 22:03 UTC, shawn-hurley commented
Let's add a quick section on the inputs and outputs to the library. 

is the library responsible for writing the files?

2021-05-12 04:30 UTC, alaypatel07 commented
I am wondering how would a crane 2.0 user handle the difference in APIs? For example, during backup, a preferred API version is available, but upon restore it is not available? The solution in velero is to backup all the versions of the resource that increases the chance of one of the versions being available during restore. We also can handle this out of band in transform. I am just trying to nail down if we need to expose a flag for backing up all the version of the same object?

2021-05-17 15:31 UTC, shawn-hurley commented
I think conversion should be a seperate tool WDYT?

2021-05-18 16:00 UTC, alaypatel07 commented
> I think conversion should be a seperate tool WDYT?

make sense, +1

> Let's add a quick section on the inputs and outputs to the library.


Updated.

2021-05-18 16:03 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> + interface, and the namespace which needs to be backed up
Could this be a list of namespaces?

2021-05-18 16:04 UTC, shawn-hurley commented on enhancements/crane-2.0-discovery/README.md
> +- the output will be a
I think you probably need a list of "namespace output" and then the maps are in the namespaced outputs WDYT?

2021-05-18 16:08 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> + interface, and the namespace which needs to be backed up
My thought was to start with a single namespace, if we need a list of the namespace, make a decision then once we have a rough outline of the code.

2021-05-18 16:09 UTC, alaypatel07 commented on enhancements/crane-2.0-discovery/README.md
> +- the output will be a
Same, start with a single namespace, I am debating with myself if returning a namespaced map would be better or calling this function with multiple namespaces in a loop would be better. Can we defer this decision?

2021-05-18 16:48 UTC, shawn-hurley approved these changes
Yep I agree defer decisions or stick with this and make the caller choose to make it a list or what not +1

2021-05-18 16:48 UTC, shawn-hurley approved these changes
Yep I agree defer decissions or stick with this and make the caller choose to make it a list or what not +1

2021-05-18 19:47 UTC, merged