State Only Migrations
konveyor/enhancements pull request #26
Opened 2021-06-16 18:02 UTC by pranavgaikwad

2021-06-16 18:38 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +
@shawn-hurley Shawn commented on the other PR I opened which was merged by mistake:

```
I would like to see an alternative added, around not using a new itinerary and instead of moving things in the direction that uses sub-controllers for a "phase" with events being the mechanism for stating progress and status for reporting what sub-controller or "phase" it is in.
```

2021-06-16 19:23 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +
@eriknelson Erik asked for an alternative approach as well.

2021-06-18 19:34 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +type PVC struct {
Is this a list of PVC objects?

2021-06-18 19:57 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +By default, _StateTransfer_ will include following resources:
Is there an alternative here to just exposing these as fields on the migplan only, and keeping stage and final migration the same?

2021-06-18 20:00 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +	IncludedResources string `json:"includedResources,omitempty"`
When this field is empty what does that mean? it will use the above list? how do I tell it no resources for only state PVC migration? How does this field get used or ignored when used in stage or final migrations.

2021-06-18 20:02 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +State only migration does not aim to include all the resources from source namespaces in a migration. Instead, it will give the users a label they can add on their resources.
Does this then work with final migrations?

2021-06-25 20:40 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +State only migration does not aim to include all the resources from source namespaces in a migration. Instead, it will give the users a label they can add on their resources.
Please see [compatibility matrix](https://github.com/pranavgaikwad/enhancements/blob/master/enhancements/state-only-migrations/README.md#final-migration-compatibility) in the updated doc @shawn-hurley

2021-06-25 20:41 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +	IncludedResources string `json:"includedResources,omitempty"`
Please see compatibility matrix in the updated doc

2021-06-25 20:41 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +By default, _StateTransfer_ will include following resources:
Maybe answered in the updated doc

2021-06-25 20:41 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +type PVC struct {
Yes, this is a list of PVC objects in the MigPlan API.

2021-06-28 16:19 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
some questions regarding this section?

1.  `the PVs will be already provisioned` it says that PVs will be already provisioned, does that mean that the PVC for it will exist? 
2. if yes to the above answer, should we call out that the PVC name on the destination can be different from source ?
3. If yes to the above answer, what happens if data is already present on the PVC on the destination? will it be wiped out and the data will look an exact mirror of the source? or would we merge the data? if merge, how would we handle conflicts?

2021-06-28 16:21 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +#### Selecting PVs
Do you mean selecting PVCs?

2021-06-28 16:54 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
what would happen if the user configures the LabelSelector but does not configure the `IncludedResources`?

Are both the `IncludedResources` and `LebalSelector` separate features that could work irrespective of the other or will label selector only be applied if IncludedResources is not empty?

2021-06-28 17:51 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
> One of the safer solutions is to patch the namespace before migrating PVs

So this is safer solutions from a migration perspective, but not really safe for the user right? for example, assume that the there is another namespace in the destination cluster with the same annotations as the source and a user in that namespace has access to hostPath. They could have access to the data of migrated namespace right?

Instead can we call out here that "when migrating to different namespace/PVC there will be permissions issues will will be mentioned in a separate enhancement in the future, for now we will document the various options that user has and they could decide which one is safe for them to move forward" ?

2021-06-28 17:53 UTC, alaypatel07 requested changes
The API looks good to me. Had some questions on other sections of the implementation, PTAL

2021-06-28 18:44 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
@alaypatel07 
1. Yes, it is assumed that the PVs will be provisioned as a result of pre-existing PVC in the target namespace. The PVC will be a part of application YAML definition stored in Git. 

2. Yes, mapping of names assumes that the PVC name will be different, we don't care about PV name.

3. The default behavior would be to wipe out existing data and replace it with source data making it a clone of source. This can be adjusted at Rsync level using different options. However, we only consider default use case of overwriting.

2021-06-28 18:45 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +#### Selecting PVs
Yes, I am into habit of using PV <-> PVC interchangeably, but in general, this entire document assumes that for every PV, there is an associated PVC.

2021-06-28 18:47 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
@alaypatel07 all of the different scenarios are explained in the compatibility matrix in the Upgrade/Downgrade section. But to answer your question, yes! Both the settings can be used independently, meaning, empty list of included resources with a non-empty label selector implies that all the resources that match the label will be included.

2021-06-28 18:49 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@alaypatel07 I just wanted to include this section to note down the "risk". The proposed solution is one of the different solutions we will be considering. I believe that the problem requires its own enhancement doc and we keep this section as-is just to call out the possibility of failures.

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
I was slightly confused by the wording as well, leading to my own version of 1) in my head. Maybe a minor wording change above -- from "and the PVs will be already provisioned in the target cluster" to "and the PVs will be already provisioned in the target cluster bound to PVCs" -- later sentences make this clearer already, but if you make it clear from the first mention of that use case that we'll be copying into already-existing (and possibly already mounted) PVCs, this will make it clearer.

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
Also, note that if the applications have already been deployed to the target/dest cluster, then we may run into similar RWO-oriented challenges as we have on the source cluster when not quiescing. If it's not already in the design, you may need to offer a similar quiesce option on the target cluster here -- quiesce apps, dvm/rsync to the volumes, un-quiesce.

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +The users will be able to select PVs to be included in the migration in the UI. This will be achieved by setting `PvSkipAction` on any PVs excluded from the migration. This is already possible in our
You may need some minor changes to the PvSkipAction. I think right now we only allow skipping PVCs which are *not* connected to source cluster applications. The thinking was that since MTC doesn't allow the user to skip particular deployments, we don't allow users to skip that deployment's PVCs either. However, if there are PVCs that are currently unconnected to applications, those *are* skippable. We may need to relax this restriction to enable state only migrations.

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +type PVC struct {
So the *namespace* will be constrained by the migplan's namespace-to-namespace mapping. This means that within a namespace, any PVC can be mapped to any new name, but all PVCs in a particular source namespace must be mapped to other PVCs in the same target/dest namespace (same as each other, not necessarily the same as src). In other words, if src has ns1/pvc1, ns1/pvc2, ns2/pvc3, ns2/pvc4, then you could map those first two ns1 PVCs to ns5/pvc10 and ns5/pvc11 but you couldn't map those to ns5/pvc10 and ns6/pvc11.

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +type PVC struct {
(to be clear, the above applies to migplan-driven migrations. A raw DVM resource created could map any PVC to any other PVC, since in the DVM CR, the only place PVC namespaces are identified is within a single PVCToMigrate struct)

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
@alaypatel07 Since these are just being passed on to velero, the two act independently. include/exclude are related -- if exclude is given but include is not, then the effect is "everything except exclude", but if include is given, then only those resources are included. Then, in addition to this, if a label selector is given, then once we have a full list of resources to back up from the include/exclude lists, that list is then filtered on a per-item basis using the label selector. This is how we do stage backups today. We have a limited set of included resources (PVCs, ImageStreams, etc.) *and* a label selector (the IncludedInStageBackup label).

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
@pranavgaikwad Are these includes/labels only being used for final backup? For stage are we using the existing label and include list?

2021-06-28 22:51 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@alaypatel07 " assume that the there is another namespace in the destination cluster with the same annotations as the source and a user in that namespace has access to hostPath. They could have access to the data of migrated namespace right" -- note that this is also a problem today in current (and prior) versions of MTC, since we also create the namespace with that UID range which may be in use in the target cluster already.

2021-06-29 01:03 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
> Yes, mapping of names assumes that the PVC name will be different, we don't care about PV name.

Since PVC is the unit of data transfer, can I ask to refactor this entire doc to remove all usage of PV and replace it with PVC?

> The default behavior would be to wipe out existing data and replace it with source data making it a clone of source. This can be adjusted at Rsync level using different options. However, we only consider default use case of overwriting.

Sounds fair to me as long as this is explicitely documented. Can you please include this in the doc?

2021-06-29 01:12 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@sseago noted, but I believe, with this new work there is an opportunity at solving that shortcoming.

@pranavgaikwad I agree that noting down the "risk" is the right thing to do, and I also agree that this enhancement does not intend to provide the solution, but doesnt the following do exactly that i.e. suggest a solution?

> One of the safer solutions is to patch the namespace before migrating PVs such that the annotations are equal to that of source ns. If there are any workloads running in that ns already, the workloads need to be queisced and unquisced once post update.

2021-06-29 14:49 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
Why can't I pre-create a volume and put data there with this feature? 

Why are we assuming that the PVC would be created and the pipeline would be run before transferring the data?

2021-06-29 15:06 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +#### Selecting PVs
> I really would like us to consider if PV is the correct thing to consider here.

I don't really think that is possible. I would love to see what I am missing.

2021-06-29 16:36 UTC, shawn-hurley reviewed
I believe that Alay is correct regarding the PV thing and that I am wrong.

I think this enhancement from an API sense makes sense I would just make sure two things:

1. That any absence of values means that all values are used to preserve backwards compatibility,
2. That these fields are 100% optional and them not existing is equal to the absence of the value.

2021-06-29 16:36 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
I think I would suggest that we consider that for now, we force a user to take an action and just warn them when this happens? Do we have the ability to do that?

2021-06-29 16:36 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +| No 	|   Resources in source ns   	| Global exclusion list 	| MigPlan inclusion list 	| Label Selector 	|           Outcome          	|
Are A B and C GVK's?

2021-06-29 18:37 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
@shawn-hurley We're using this to set `IncludedResources` on the velero backup spec, so we need to use the same format as velero. For example, for a current MTC stage backup, we'd have something like this:
```
  includedResources:
  - serviceaccount
  - persistentvolumes
  - persistentvolumeclaims
  - imagestreams
  - secrets
  - configmaps
  - pods
```

2021-06-29 18:39 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
From the velero BackupSpec struct definition:
```
        // IncludedResources is a slice of resource names to include
        // in the backup. If empty, all resources are included.
        // +optional
        // +nullable
        IncludedResources []string `json:"includedResources,omitempty"`
```

2021-06-29 18:49 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +| No 	|   Resources in source ns   	| Global exclusion list 	| MigPlan inclusion list 	| Label Selector 	|           Outcome          	|
Yeah, I should have been more clear on the naming. Yes, alphabets are GVKs and digits are the labels added on instances of them.

2021-06-29 18:49 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
I would really prefer this be a GVR or a GR. 

I assume that those work for core types but what about non-core types?

2021-06-29 18:52 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
We really can't do anything other than "what velero does" since we're passing them directly over. I haven't actually looked at the internal velero parsing code directly to know the limits of what is parsed out of this, but they certainly do work for non-core types, CRDs, etc.

2021-06-29 18:54 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
We can pass that down, however, velero needs, that doesn't mean that our API has to look at the same if there is a better way?

2021-06-29 18:57 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
If we want to create our own custom spec field, parse it, and generate the velero backup.Spec.IncludeResources in a way that works for velero, nothing is stopping us. Whether this is a "better way" is not at all clear to me, though. We'd need to identify what we would gain for this extra effort.

2021-06-29 18:58 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
Here's where Velero deals with individual elements of this slice:
https://github.com/vmware-tanzu/velero/blob/main/pkg/util/collections/includes_excludes.go#L202

2021-06-29 19:14 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
@sseago yes, just the final backup. Stage Backup remains untouched

2021-06-29 19:14 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@shawn-hurley we currently don't have that ability. However, it is not hard to implement in DVM. Good point.

2021-06-29 19:16 UTC, shawn-hurley commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
If I wanted to exclude deployments today, what string do I need to add?

2021-06-29 19:21 UTC, sseago commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
If IncludeResources is non-empty, you just need to make sure that "deployments" isn't there. A non-empty IncludeResources means that only the listed resources are included. If IncludeResources isn't specified, then everything *except* ExcludeResources is included.

2021-06-29 19:28 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@alaypatel07 risks and mitigations :)

2021-06-29 20:26 UTC, alaypatel07 commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
fair @pranavgaikwad

2021-06-30 16:50 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
@shawn-hurley As Scott suggested, having a GVK list in our API means that we have to do reverse of what Velero is doing to get GVK from the short names and then pass that list to Velero. Keeping it a list of strings means that we don't need that other logic.

2021-06-30 16:51 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +It is assumed that the most Kubernetes resources will be migrated externally. There are two possible scenarios in this case - either the PVC objects will not be migrated externally or the PVC objects
@alaypatel07 updated

2021-06-30 16:53 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +If a namespace was created as a result of GitOps/Pipeline deployment in the target cluster, it is possible that the UID range of the namespace in the target cluster differ from that of the source. In
@alaypatel07 called it out specifically that this problem will be addressed separately.

2021-06-30 17:58 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +	IncludedResources []string `json:"includedResources,omitempty"`
@shawn-hurley @sseago As we discussed offline, it appears that everyone is in fact in agreement on changing this from a string slice to a structured type. We will also propose to update the upstream Velero api to make the inclusion lists structured. As for MTC, irrespective of what Velero does, we will stick with the structured types, most likely `metav1.GroupResource`.  Until Velero accepts the change, we will hide the conversion in MTC.

2021-06-30 18:15 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +The users will be able to select PVs to be included in the migration in the UI. This will be achieved by setting `PvSkipAction` on any PVs excluded from the migration. This is already possible in our
@sseago Updated the document to specify this catch.

2021-06-30 18:16 UTC, pranavgaikwad commented on enhancements/state-only-migrations/README.md
> +| No 	|   Resources in source ns   	| Global exclusion list 	| MigPlan inclusion list 	| Label Selector 	|           Outcome          	|
I added a footer to the table explaining what is what. I believe that answers your question. Resolving!

2021-06-30 21:11 UTC, shawn-hurley approved these changes

2021-07-01 15:32 UTC, sseago approved these changes

2021-07-01 15:54 UTC, pranavgaikwad commented
Since we have 2 approvals out of 3, I am going ahead and merging this PR. Thank you all for your inputs.

2021-07-01 15:55 UTC, merged