transform plugin priorities design
konveyor/enhancements pull request #28
Opened 2021-06-24 20:43 UTC by sseago

2021-06-24 21:16 UTC, alaypatel07 commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +plugin. The user should be able to provide a non-exhaustive list of plugin names in
does this mean that we expect the user to know what result each plugin is producing in detail?

2021-06-24 21:17 UTC, alaypatel07 commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +The `Summary` section is incredibly important for producing high quality
needs to be removed?

2021-06-24 21:29 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +plugin. The user should be able to provide a non-exhaustive list of plugin names in
@alaypatel07 Possibly. For example they have a custom plugin that overrides one of our out-of-the-box ones. Another possibility is that the user did an initial transform run, noticed that there was a conflict, decided that the operation that was thrown out was one they wanted, so they re-ran with the priority applied. That's why priority is a function of a transform operation and not inherently tied to the plugin.

2021-06-24 21:29 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +The `Summary` section is incredibly important for producing high quality
Yes -- I'll pull it out on the next revision.

2021-06-25 18:53 UTC, shawn-hurley requested changes
Nits and a point of clarification other than that it looks good to me.

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +What should the CLI flag be for "plugin-priorities", as "-p" is
For now, let's just not give it a short name and only make it a long name? WDYT?

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
Really quick point of clarification to make sure I am following:

The goal is for the runner to be able to select on a per transform action which one to choose. 
The user interface is not per transform action, rather is on a plugin in basis I thought?

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +```
nit: add go here for pretty rendering

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +`PluginPriorities` will be a mep of plugin name keys and priority
nit: s/mep/map

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +When the runner calls SanitizePatchesm this `PluginOperation` list
nit: s/SanitizePatchesm/SanitizePataches

2021-06-25 18:53 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +type BinaryPlugin struct {
nit: Missing name Field

2021-06-25 18:57 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +What should the CLI flag be for "plugin-priorities", as "-p" is
Works for me.

2021-06-25 18:59 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
I think the original wording here reflects my understanding of how this works (and how I've explained it below), but perhaps it's not clear enough? The priorities passed in are based purely on plugin name, but priorities are only valid for *this* transform. If you run it again without selecting priorities, we're back at using the default "no priorities" and the plugins which appear first in the conflict win. I think the only clear way to describe this is "plugin priorities for this transform command invocation", which re-stated as a goal is what I have above. Is there a better way to phrase it here so that the meaning is clearer?

2021-06-25 19:01 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
If options end up eventually specified via env vars, then in fact a given set of options (including priorities, but also export dir, etc.) will be used across multiple transforms, but that's a side effect of the way environment variables work. The command options are still specified on a per command invocation basis.

2021-06-25 19:02 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
But maybe the confusion here is "transform action" of a single plugin vs. "transform action" -- i.e. the user action of running the transform command which invokes multiple plugins across multiple resources. The latter is what I mean. Perhaps "per-transform-command-invocation" is clearer?

2021-06-25 19:03 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +When the runner calls SanitizePatchesm this `PluginOperation` list
s/SanitizePataches/SanitizePatches, but yes.

2021-06-25 19:18 UTC, shawn-hurley commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
Or make it clear the goal is about the CLI and not the library bits. I would probably say "Ability to choose, for a CLI transformation run, which plugins...." Or something like that. 

I agree what I stated above and what you describe down below are the same.

2021-06-25 19:22 UTC, sseago commented on enhancements/crane-2.0/transform-plugin-priority/README.md
> +- Ability to choose, on a per-transform-action basis, which plugins
How about this (based on your last suggestion):
```
- Ability to choose, for a single CLI transformation run, which plugins (if any) should take precedence
```

2021-06-25 19:56 UTC, sseago commented
Feedback received so far has now been addressed.

2021-06-25 20:09 UTC, shawn-hurley approved these changes
Looks good to me

I think that we need to add an issue to cover the need for the runner to determine conflicts in operations for the same path, I don't think that sanitizePatches does that today

2021-06-25 20:31 UTC, sseago commented
@shawn-hurley That's right. I think different operations on the same path don't register as a conflict. I think the answer there is to just stop using the Kind+Path operation key struct and just use the Path as a string key for patchMap. I'll create a crane-lib issue and we can discuss the fix there, though. That's an issue that's largely orthogonal to this one (although the fixes will modify the same code)

2021-06-25 20:36 UTC, sseago commented
@shawn-hurley https://github.com/konveyor/crane-lib/issues/32

2021-06-28 14:53 UTC, merged