DVM Crane State Transfer Feature Parity
konveyor/enhancements pull request #31
Opened 2021-06-28 15:07 UTC by pranavgaikwad

This is a feature parity enhancement document created to propose solutions to different DVM features we want to implement in Crane 2 to maintain feature parity. This is also a follow-up on the previous State Only Migrations doc I proposed. It will address the implementation details for the API changes proposed in the state only mgirations as well.

2021-06-29 01:24 UTC, alaypatel07 commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	SetDefault()
I am having little trouble understanding this interface. 

So from my understanding of looking at the interface mentioned above, the `CreateClient` method of the interface is supposed to use the Rsync options. When the CreateClient function is called can you help me understand how do you see the usage of the methods of this interface to populate the Client pod?

2021-06-29 13:56 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	SetDefault()
The usage of validate() doesn't populate the Client Pod. Everytime a transfer uses its options, it calls the `Validate()` method,  if the method returns an error, `SetDefault()` will be called to set a sane default.

2021-06-29 14:34 UTC, alaypatel07 commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	SetDefault()
So after calling `SetDefault()` you still need to take those options and convert them into rsync command right? How would that work with the interface?

2021-06-29 19:20 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	SetDefault()
@alaypatel07 this interface is just impose an agreement on Transfer options that they need to be validated by someone, or at least that is the intention behind the design. The someone in this case will be the Transfer which is using those options. See down below the concrete implementation for RsyncTransferOptions

2021-07-01 19:24 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +#### Allowing custom labels and custom Rsync options for Rsync Transfer
Please see a sample here: https://github.com/pranavgaikwad/crane-lib/blob/dvmParity/state_transfer/transfer/rsync/options.go

2021-07-02 17:16 UTC, alaypatel07 commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +type RsyncResourceMetadata struct {
could we reduce the number of fields in this struct to half? 
```
ReourceMetadata struct {
	Labels                 map[string]string
	Annotations            map[string]string
	OwnerReferences        []metav1.OwnerReference
	SecurityContext        *corev1.SecurityContext
}
```

And then we use two different instances for sourcePods and destinationPods?

2021-07-02 17:34 UTC, alaypatel07 commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	RsyncResourceMetadata
I would expect the ResourceMetadata to be a more generic field shared by all the packages and not be hidden in rsync package. For example, even the routes and services we create in the endpoint package would need those right?

2021-07-02 18:08 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +type RsyncResourceMetadata struct {
@alaypatel07 makes sense. I would assume at the transfer level or maybe even one level above for transport, endpoint and transfer all

2021-07-02 18:08 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +type RsyncResourceMetadata struct {
@alaypatel07 +1

2021-07-02 18:09 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	RsyncResourceMetadata
@alaypatel07 yeah, makes sense. maybe at the top level for endpoint, transfer and transport all

2021-07-06 17:19 UTC, shawn-hurley requested changes
Can you make sure that you delete the empty file from the commit as well?

2021-07-06 17:19 UTC, shawn-hurley commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +_Please note that the existing absolute objects are replaced with a memory reference instead to allow 'nil' checks by the consumer_
If these are unexported, are you suggesting that the nil check would happen from a call to `if pvc = t.SourcePVC(); pvc == nil {`  type of thing?

Would we consider a missing source or dest PVC an error that a user should handle?

2021-07-06 17:19 UTC, shawn-hurley commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	RsyncResourceMetadata
I would suggest we consider how we would add something similar to this, but for a different type of transfer. 

I wonder if for now we can hide the rsync bits if they are at the top level, and add validation that a given config value can be used by a concrete transfer type?

2021-07-06 17:19 UTC, shawn-hurley commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +### Implementation Details/Notes/Constraints [optional]
If none, can we remove it?

2021-07-08 17:16 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +_Please note that the existing absolute objects are replaced with a memory reference instead to allow 'nil' checks by the consumer_
@shawn-hurley yeah, not just consumer but even within the system itself, I think memory addresses are better because the objects get fiilled with default values. I also agree that a nil PVC should trigger an error so that the consumer knows something is wrong

2021-07-08 17:17 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	SetDestinationPVC(*v1.PersistentVolumeClaim)
@shawn-hurley my objective here was to just split definitions of source and target PVCs, I copied the existing method signatures. I agree to your point though that these things should only be created once at the time of Transport creation and core properties of a transport should be immutable

2021-07-08 17:19 UTC, pranavgaikwad commented on enhancements/crane-2.0/dvm-crane-feature-parity/README.md
> +	RsyncResourceMetadata
@shawn-hurley would you explain, I don't think I follow. At the time I was writing this, I couldn't imagine something common that could apply to all transfers

2021-09-30 19:27 UTC, alaypatel07 approved these changes
ACK

2021-09-30 19:28 UTC, merged