Add alternate (remote install) enhancement for CRD v1beta1 removal
konveyor/enhancements pull request #39
Opened 2021-07-21 19:30 UTC by djwhatle

2021-07-22 16:20 UTC, shawn-hurley reviewed
Thank you for having both proposals created! this is making it a really open discussion that I think is great!

2021-07-22 16:20 UTC, shawn-hurley commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Common migration scenarios can be handled with this strategy:
I think we should add the restricted network migration here as well

2021-07-22 16:20 UTC, shawn-hurley commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Alternatively we could include this config info directly on the MigCluster CR. This would require us to worry about schema changes, whereas the ConfigMap approach would be schema-less similar to how
Is there a potential versioning upgrade/downgrade problem here?

I think we need to add an upgrade downgrade section to talk about this change

2021-07-22 16:20 UTC, shawn-hurley commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Currently, mig-operator sets up the `migration-controller` SA that we use to perform actions on the remote cluster. We would need the cluster admin of that cluster to create an SA token for us instea
Would we have a published role that they would need to use?

2021-07-22 19:06 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Currently, mig-operator sets up the `migration-controller` SA that we use to perform actions on the remote cluster. We would need the cluster admin of that cluster to create an SA token for us instea
@shawn-hurley this role is used today, and could be handed to the user to create on their cluster: https://github.com/konveyor/mig-operator/blob/5a8ce7209b9a62b8afa66fafb877ad0a5d0fbb85/roles/migrationcontroller/templates/mig_rbac.yml.j2

2021-07-22 19:09 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Alternatively we could include this config info directly on the MigCluster CR. This would require us to worry about schema changes, whereas the ConfigMap approach would be schema-less similar to how
I mention some upgrade considerations in the `Risks and Mitigations` section, I'll create an upgrade/downgrade section and consolidate notes there.

2021-07-22 19:11 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Common migration scenarios can be handled with this strategy:
+1, will add.

2021-07-22 20:34 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Common migration scenarios can be handled with this strategy:
@shawn-hurley section added.

2021-07-22 20:34 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Alternatively we could include this config info directly on the MigCluster CR. This would require us to worry about schema changes, whereas the ConfigMap approach would be schema-less similar to how
@shawn-hurley section added.

2021-07-23 18:07 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +### Common migration scenarios affected by this enhancement:
@eriknelson @jwmatthews before proceeding with this plan for v1beta1 CRD deprecation, I'd like to make sure you guys are OK with these effects.

2021-07-23 18:36 UTC, jwmatthews commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +### Common migration scenarios affected by this enhancement:
We need to ensure we have a path forward for on-premise -> cloud.  I am assuming at moment that a worst case situation is the path forward is for the user to open a VPN/VPC connection between on-prem/cloud.  The burden of doing that is not desirable, but I think it would be a possibility.   I would like to discuss this with @tsanders-rh and @mberube99 next week to get their thoughts if this burden is acceptable or too great for our users.

Let's ensure we do continue to investigate if we can provide a temporary alternative with the stunnel approach or something else.   Let's not lose that as desired when we work this story.

2021-07-23 18:37 UTC, jwmatthews commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +  - OCP 3.9+: Install Crane dependencies remotely
@djwhatle 
Is this truly 3.9+ and not 3.7+?  If this is really 3.9, please help me learn what we are lacking in 3.7 to not support it.

2021-07-23 18:38 UTC, jwmatthews commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +- **OCP 4.5- to 4.5-**
I don't see this as a problem, we need to ensure we can migrate to the latest OCP releases, probably will need to support the latest 4.x EUS and latest ~2-3 releases in general.

2021-07-23 18:39 UTC, jwmatthews commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +- **OCP 3.9+ to 3.9+**
I don't see this as a problem, sounds like a reasonable trade off to lose

2021-07-23 18:48 UTC, jwmatthews commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Common migration scenarios can be handled with this strategy:
@djwhatle I'm not sure if "restricted network migration" refers to the on-prem -> cloud case where we only have network access in one direction or if it refers to the "Disconnected" scenario where a customer is running both clusters in a restricted environment with limited outside connectivity.

Please consider if we need to worry about the "Disconnected" scenario, how would we install the images for the OCP3 cluster if they need to follow the mirroring procedures for getting images into the local network.  I think it'd be worth calling that out in this doc.

2021-07-23 19:03 UTC, alaypatel07 commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Currently, mig-operator sets up the `migration-controller` SA that we use to perform actions on the remote cluster. We would need the cluster admin of that cluster to create an SA token for us instea
would be worth going through those. The particular example cited is a developer backdoor, not intended for users to muck with, in which cases when needed we should be able to jump on customer calls and edit the cluster role on remote cluster after creation.

2021-07-23 19:16 UTC, alaypatel07 commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
Deleting mig-operator.yaml deletes the entire namespace, i.e. including the service account that has gives the control cluster access to this remote cluster. If we attempt that before step 7 which needs access to the remote cluster from control cluster, I wonder if this will work. 

Give the above I might have some suggestions on this upgrade path:

1. copy all the config found in migrationcontroller.spec on the remove cluster to local configmap
2. scale down the mig-operator deployment to 0, that will stop mig-operator pod reconciling the migrationcontroller CR
3. start the mig cluster re-provisioning of velero, restic and mig-log-reader

I think the advantage of the above would be that we will not try to delete everything and restart, just update the things that are needed in place from the control cluster. We will stop the mig-operator pod that will stop all reconciling and the migraitoncontroller CR will essentially be dormant.

2021-07-23 19:19 UTC, alaypatel07 approved these changes
Added some nits. I also want to highlight one more thing, we don't have remote watches as of now. When reconciling from the control cluster do we plan on introducing them back or will this happen on a polling basis?

Apart from those details, the overall framework set up in the enhancements looks good to me.

2021-07-23 19:29 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +  - OCP 3.9+: Install Crane dependencies remotely
That's a typo, will fix.

2021-07-23 19:31 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +### Common migration scenarios affected by this enhancement:
@pranavgaikwad and I will sync on Monday to discuss possibilities

2021-07-23 19:31 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Currently, mig-operator sets up the `migration-controller` SA that we use to perform actions on the remote cluster. We would need the cluster admin of that cluster to create an SA token for us instea
ACK, good call out

2021-07-23 19:36 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
@alaypatel07 is the idea to just leave the MigrationController CR on the source cluster in a dormant state permanently until the user intervenes?

I like the idea of a scale down instead of deletion.

2021-07-23 19:38 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
@alaypatel07 does OLM not enforce 1 replica of mig-operator?

2021-07-23 19:40 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
@alaypatel07 integrated your suggestion.

2021-07-23 19:44 UTC, alaypatel07 commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
AFAIK OLM does not enforce 1 replica, would be good to fact-check here though.

2021-07-23 19:48 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +Common migration scenarios can be handled with this strategy:
@jwmatthews added section on disconnected, will sync with @jmontleon on Monday to get more details and fill in gaps.

2021-07-23 19:51 UTC, alaypatel07 commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
@djwhatle also you will have to keep migrationcontroller CR to keep the connection to the cluster. The MigrationController CR has owner reference on the migration-controller SA, if you delete that, SA will be deleted and the token will be invalidated and the control cluster will lose access?

2021-07-23 19:54 UTC, djwhatle commented
> I also want to highlight one more thing, we don't have remote watches as of now. When reconciling from the control cluster do we plan on introducing them back or will this happen on a polling basis?

Given this limitation (we can't watch on a remote cluster):

- Option 1: assume user won't delete Deployments and ConfigMaps we put into `openshift-migration`. This seems like a reasonable thing to expect of users IMO.
   - If they do, require them to recreate their MigCluster to get their provisioned items back.

- **Option 2:  Run periodic checks to see if everything needed on remote end is still installed and in correct state.** If things don't look correct, enqueue a MigCluster reconcile. Putting this poll for correctness outside the main  reconcile  will avoid triggering reconcile of ~500 plans when not needed.
    - Example:  [RemoteClusterSource](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migcluster/migcluster_controller.go#L79-L87)

2021-07-23 20:04 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +#### Automatic Upgrade steps (Crane 1.5 to 1.6+):
> if you delete that, SA will be deleted and the token will be invalidated and the control cluster will lose access?

@alaypatel07 that's a good point, so we will need to keep that around then.

> AFAIK OLM does not enforce 1 replica, would be good to fact-check here though.

I just verified that OLM allows you to scale mig-operator to 0 replicas.

2021-07-23 21:01 UTC, alaypatel07 commented
> This seems like a reasonable thing to expect of users IMO. There's no difference in this vs. expecting the user to not delete their MigrationController CR I don't think.

@djwhatle Fair point. In fact, I would argue this is safer because the user will have to log into the source cluster for anything. It helps to avoid unintentional mistakes.

2021-07-27 14:16 UTC, djwhatle commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +### Common migration scenarios affected by this enhancement:
@jwmatthews are any specifics available on the exact network configurations we must support? That would help with determination of whether we can work out a communication method.

2021-07-27 19:13 UTC, eriknelson requested changes

2021-07-29 17:05 UTC, sseago commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +- __2__. Velero 1.6.z is planned to be be out-of-support upstream, which means that we may need to backport CVE and certain bugfixes (essentially blocker bugs that affect backup creation), since upst
@eriknelson So in some cases, we get notified of CVEs affecting our velero builds before upstream fixes them -- that's what happened with the 1.6.2 CVEs. But there is a risk for CVEs that are reported directly to upstream that we don't know about -- for those, it's possible that velero 1.7+ for OCP4 clusters get fixed but our OCP3 1.6.3 velero release does not. It may be that "read through Velero release notes and investigate any CVEs mentioned" needs to be part of our 1.7+ rebase process.

2021-07-29 17:05 UTC, sseago commented on enhancements/crane-1.x/crd-v1beta1-deprecation-remoteinstall/README.md
> +- __2__. Velero 1.6.z is planned to be be out-of-support upstream, which means that we may need to backport CVE and certain bugfixes (essentially blocker bugs that affect backup creation), since upst
It's probably worth noting that when the up-to-date velero updates to a new restic version, the same concerns apply there -- we need to investigate the restic changes and determine whether we want to either upgrade restic for our 1.6 velero stream or cherry-pick specific security fixes onto our restic fork of 0.12.0.

2021-07-29 19:17 UTC, djwhatle commented
Merging this as deferred, since we will plan to look at remote install work again in Crane 1.7.0 timeframe. Plan for now is to go with https://github.com/konveyor/enhancements/pull/35 for Crane 1.6.0.

2021-07-29 19:22 UTC, merged