Progress reporting enhancements
konveyor/enhancements pull request #4
Opened 2020-09-16 16:46 UTC by pranavgaikwad

Proposing enhancements in MTC progress reporting

2020-09-16 16:53 UTC, djwhatle commented
@pranavgaikwad can you add Jeff as a reviewer in the enhancement?

2020-09-17 16:27 UTC, jortel commented on enhancements/progress-reporting/README.md
> +  step: Backup
The `Reason` in the Running condition communicates the current _step_ to the user.  Currently it is 1-1 with the phase but was designed with the mapping in mind for decoupling.  How about using it instead of a new `step` field?

2020-09-17 17:50 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +  step: Backup
@jortel Okay. The idea behind introducing this field is to let UI know which broader step in the Migration the current phase belongs to. The word `step` might not be appropriate given the current usage of the word in the context of progress.

2020-09-17 18:00 UTC, jwmatthews commented on enhancements/progress-reporting/README.md
> +
@pranavgaikwad I saw the below mentioned deeper in the document, I think this captures the most important goal for this effort, please add this to the first paragraph to reemphasize

"user will have enough information in their hands to understand what exactly is happening in the background"

Thinking something like:

The goal of this document is to highlight user experience issues in the current implementation of progress reporting in MTC, and propose improvements in some of the areas for a better user experience.  

**The driving goal of this work is to ensure the user has enough information in their hands to understand what exactly is happening in the background.**

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +- Prepare: Created, Started, Prepare, EnsureCloudSecretPropagated
@jortel phase to step mapping.

@pranavgaikwad, Jeff had the idea to change the itinerary struct to allow it to be broken up into ordered `Steps`

This would allow us to avoid maintaining a separate mapping. Would also allow `Steps` to contain different phases per itinerary if it makes sense for us.
```
Itinerary
    Step Backup
        Phase InitialBackup
        Phase WaitForBackup
    Step Restore
       ...

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +      progress: 6/9 items backed up
+1 to adding a progress field.

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +      reason: StageBackupCreated
@jortel and I were talking about putting  the new `Step` into this `Running` condition `Reason` slot. mig-ui is supposed to consume all progress info from this condition.

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +* Final
I like the names you've chosen here, but `Final` is unclear to me. Maybe `Cleanup`? Open to other ideas.

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +- Final: MigrationFailed, EnsureStagePodsDeleted, EnsureAnnotationsDeleted, DeleteMigrated, EnsureMigratedDeleted, UnQuiesceApplications, Completed
Just FYI, the work @aufi is doing will change the Failed and Cancel itinerary substantially.

2020-09-17 23:18 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +Having a fixed number of steps will make it possible for us to implement a pipeline type progress view in the UI.
+1 to thinking about future pipeline support.

2020-09-18 15:07 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +* Final
@djwhatle I was unsure about `Final` too. We want something that doesn't just capture the cleanup phases but also Verification and Completed phases

2020-09-18 15:08 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +      reason: StageBackupCreated
@djwhatle +1 makes sense

2020-09-18 15:08 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +- Prepare: Created, Started, Prepare, EnsureCloudSecretPropagated
@djwhatle +1 to updating struct.

2020-09-21 20:12 UTC, djwhatle requested changes
@pranavgaikwad I think we can merge this as "implementable" after a few changes:

1. Needs update to intro section re: John's comment
2. Needs to incorporate mention plan to modify the itinerary struct (instead of keeping a totally separate mapping of [phases] -> [step])

I think we could stick with "Final" as the working name for now. It's easy enough to change later, but don't want to block implementation on this.

2020-09-22 02:00 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
@pranavgaikwad I wonder if we should add
1. naming the phases appropriately and 
2. adding description to the phase either in documentation or mig cr

as solution solving the same problem, i.e. improving visibility to user on whats happening

2020-09-22 02:02 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +1. Provide detailed progress information of ongoing migration phase in _MigMigration_ CR
please see the above [comment](https://github.com/konveyor/enhancements/pull/4/files#r492438380) if we can add this a second goal below this

2020-09-22 02:11 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +      progress: 6/9 items backed up
wonder if we should make this field `message` so that for phases that do not have progress to report, we can display an appropriate message. Also, how about formatting the value of this field as: `backup myAwesomeBackup is in progress, 6/9 items completed`. The idea is I would want the name/namespace from this CR so I can look up detailed yaml on source cluster if need be

2020-09-22 02:18 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +Apart from the above phases, we propose to incorporate similar progress reporting for other phases of migration, wherever possible. For example, in Stage Pod phases, We can relay the status of the po
In general, I think the convention to adopt is if a single resource is being created/updated in the phase, we should have name/namespace of that resource so it can be input to other debug steps. If there are multiple resources being updated/created, we should display `x/y updated, 1 failed, 1 in progress` etc. This is in accordance to convention being followed in openshift look here [[1]](https://github.com/openshift/cluster-etcd-operator/pull/290#discussion_r407666816)

2020-09-22 02:32 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +With the progress information relayed in the _MigMigration_ CR, we believe that the user will have enough information in their hands to understand what exactly is happening in the background. We can
IMHO I'm in a grey area if this helpful or misleading user. As a user will I like if there is a smaller number of steps(or phases, using the term to denote actual steps of migration)? Definitely yes. But because the actual process of migration is quite involved, will a user like to have a hierarchy in mig CR, `top level step -> involves multiple lower level phases`? I am not quite sure. It would be great for CI and pipeline view but honestly not too good for CLI. This hierarchy will make it hard(er) for CLI users using jsonpath (and alike feature tools) to query migmigration with `complex` and conditions. Also, we would have to come up with a way of portraying this so that hierarchy is evident. Steps and phases are not good terms for hierarchy, they might lead to confusion, will add the terms here if I can think of more apt ones.
 
In general, I think this is an add-on feature and would only like to see it being implemented if time permits after implementing other efforts in 1.4.0

/cc @jwmatthews @djwhatle

2020-09-22 02:35 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +- VolumeBackup: EnsureStagePodsFromRunning, EnsureStagePodsFromTemplates, EnsureStagePodsFromOrphanedPVCs, StagePodsCreated, AnnotateResources, RestartRestic, ResticRestarted, QuiesceApplications, En
technically this is not accurate

Stage backups now include image stream resources as well. So may rename this to `StageBackup` instead of `VolumeBackup`?

2020-09-22 02:35 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +- VolumeRestore: EnsureStageRestore, StageRestoreCreated, EnsureStagePodsDeleted, EnsureStagePodsTerminated
Same as above

2020-09-22 02:37 UTC, alaypatel07 reviewed
Added a few questions.... +1 to reporting progress

2020-09-22 13:51 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
@alaypatel07 I don't like the idea of adding documentation for each phase as its just not something user likes to do. I want to find the answer to the question of - how can we make it more implicit? How can we make the user know without having to explain them anything?

2020-09-22 13:59 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +With the progress information relayed in the _MigMigration_ CR, we believe that the user will have enough information in their hands to understand what exactly is happening in the background. We can
@alaypatel07 There won't be hierarchy in the Status field itself. The hierarchy is logical. The status field would look like:

```yml
  conditions:
  - category: Advisory
    lastTransitionTime: "2020-09-15T14:54:46Z"
    message: 'Step: 7/33'
    reason: Backup
    status: "True"
    type: Running
  - category: Required
    lastTransitionTime: "2020-09-15T14:53:15Z"
    message: The migration is ready.
    status: "True"
    type: Ready
  itenerary: Final
  phase: InitialBackupCreated
``` 
The original idea of adding a new field `step` definitely would add confusion. But as @jortel suggested, we can use the `reason` field instead to do that. Do you think this will still confuse the user?

2020-09-22 14:29 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
`adding documentation` @pranavgaikwad I did not mean to say this description is as exhaustive as documentation. but a little more verbose the one phrase. If you look at pod conditions, it has the following field which I would like to model

```
   message      <string>
     Human-readable message indicating details about last transition.

   reason       <string>
     Unique, one-word, CamelCase reason for the condition's last transition.
```

In our case the reason is the phase and message can be human readable string

2020-09-22 14:30 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +      progress: 6/9 items backed up
@alaypatel07 want to understand what you are saying.

Right now we use message for `Step 7/33`, which is a phase progress indicator:

```
  - category: Advisory
    lastTransitionTime: "2020-09-15T14:54:46Z"
    message: 'Step: 7/33'
    reason: InitialBackupCreated
    status: "True"
    type: Running
```

Are you proposing we should wipe out the phase based progress info from the status (since we'd be using the field it exists in now for something else)?

2020-09-22 14:34 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +With the progress information relayed in the _MigMigration_ CR, we believe that the user will have enough information in their hands to understand what exactly is happening in the background. We can
@pranavgaikwad in the status field you proposed, I wonder if users would be able to immediately connect Step 7/33 corresponds to `InitialBackupCreated`.  In the message field, we are calling it Step 7 of 33 but later when displaying the name we are calling it phase

2020-09-22 14:36 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
@pranavgaikwad in case you weren't aware, I've been looking at adding `detailed phase descriptions` to controller since before this sprint. I'm not sure how it will fit in with all of these proposed changes but I'm suspecting it will need to adapt. https://github.com/konveyor/mig-controller/pull/656

I'm also planning to do a round of updating the phase names to be more indicative of what is _currently_ being worked on.

2020-09-22 14:39 UTC, djwhatle commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
So to clarify, the user wouldn't need to look up detailed phase info in docs, it would be reflected on Mig status.

2020-09-22 14:47 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +With the progress information relayed in the _MigMigration_ CR, we believe that the user will have enough information in their hands to understand what exactly is happening in the background. We can
@alaypatel07 this problem is there with the current phase implementation too. Step and Phase are kind of interchangeable in their meanings.

2020-09-22 14:50 UTC, pranavgaikwad commented on enhancements/progress-reporting/README.md
> +* In a full migration, there are over 30 steps/phases involved. The migration transitions from one phase to another until completion. All these phases are posted to the Status field of the _MigMigrat
@djwhatle @alaypatel07 I get the point now. Having a `message` field with detailed description, I think makes the Enhancement 2 (grouping phases) invalid. I wouldn't call it an enhancement if we can already convey the same information through the message field.

2020-09-22 14:59 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +With the progress information relayed in the _MigMigration_ CR, we believe that the user will have enough information in their hands to understand what exactly is happening in the background. We can
@pranavgaikwad If they are interchangeable I wonder if we can replace `message: 'Step: 7/33'` with `message: 'Phase: 7/33'`?

2020-09-22 15:29 UTC, alaypatel07 commented on enhancements/progress-reporting/README.md
> +      progress: 6/9 items backed up
@djwhatle multiple options:

options 1:

```
  - category: Advisory
    lastTransitionTime: "2020-09-15T14:54:46Z"
    message: 'phase: 7/33, backup <backup-name> in progress, 6/9 completed'
    reason: InitialBackupCreated
    status: "True"
    type: Running
```

2.
```
  - category: Advisory
    lastTransitionTime: "2020-09-15T14:54:46Z"
    message: 'Phase: 7/33, backup <backup-name> in progress'
    reason: InitialBackupCreated
    status: "True"
    type: Running
     veleroBackupProgress: <struct from velero API>
``` 
and similar for restore. 

I like option one because we can make it generic for other phases, `message: Phase: x/y; a/z resources updated`

2020-09-24 17:45 UTC, alaypatel07 commented
```
status:
   phaseStatuses:
   - name: "FOO"
     startTime: "today 4pm"
     lastUpdateTime: "today 6pm"
     progress: "8/10 completed, working on 9th"
```

I wonder if adding a new status field `phaseStatuses` instead of reusing the conditions makes sense. This would serve multiple objectives:
1. a good place to update progress
2. a place to record the start time and update time for each phase status. This will help in bubbling up phases that take longer than expected. Since we have update time, what we are reporting in progress is tied to a time, so technically we are as accurate as we can be
3. ordered list of phaseStatuses will allow us to retain the information even after migrations for retrospecting. This will make the migmigration yaml larger but all the information is useful in debugging

2020-10-21 15:52 UTC, djwhatle commented
@pranavgaikwad  would you prefer to leave this open as a living doc until we have finalized changes, or should we merge as `implementable`?

2020-10-21 18:54 UTC, pranavgaikwad commented
> @pranavgaikwad would you prefer to leave this open as a living doc until we have finalized changes, or should we merge as `implementable`?

I am just addressing Alay's feedback of having a structured progress field instead of strings. I would like to get that in probably tomorrow and then the PR would be good to merge.

2021-02-02 20:49 UTC, djwhatle commented
Merging as `implementable`, @pranavgaikwad is planning to make another pass to reconcile this with whatever drift occurred during the actual implementation process.

2021-02-02 20:50 UTC, merged