Update PVC references automatically after PV migration
konveyor/enhancements pull request #44
Opened 2021-09-27 20:03 UTC by pranavgaikwad

2021-09-28 14:29 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +During a state migration, the _MigPlan_ controller will determine whether any of the PVCs are being migrated within the same cluster and in the same namespace. If that's the case, it will raise a _Wa
If I am understanding correctly this is creating a new PVC with a new name correct and then updating? How are we propose to choose this new PVC name?

2021-09-28 14:31 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +> Approach 1 will only work on "known" workload resources and will not work on workloads managed through a Custom Resource. On the other hand, Approach 2 doesn't make any changes to the original work
Can we use something like duck typing to looks for pod template spec to more "generically" handle this?

I think you still have a potential problem for operator-backed PVCs and applications but if that is the case then we may just have to document it?

2021-09-28 14:32 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +> Approach 1 will need to update user workloads automatically. This is different from MTC's previous expectations that a migration results in a clone of source resource definitions without any change
We must change certain things on source files to work on new clusters correct? (resource version for example). I wonder if this is acceptable?

2021-09-28 14:35 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +> Approach 2 is complex to implement and requires deleting the original PVC object potentially leaving the environment in a bad state. Approach 1 is easier to implement and doesn't touch original PVC
+1 

I would almost suggest if we went this approach that we would need to write a PV/PVC reclaim and re-update controller. That feels like a huge expansion of work and if anything goes wrong could be bad.

2021-09-28 14:38 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +When downgrading from 1.7+ versions to an older version, this feature will simply be absent. The extra _spec_ field present in _MigMigration_ CRs wont make any difference on the behavior of the contr
These will be ignored by ETCD as well, such that after upgrading we need to make sure the default value for this field, preserves the behavior for that resource. 

For this reason, I wonder if we need to re-consider what the default is for this field.

2021-09-28 17:02 UTC, pranavgaikwad commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +During a state migration, the _MigPlan_ controller will determine whether any of the PVCs are being migrated within the same cluster and in the same namespace. If that's the case, it will raise a _Wa
@shawn-hurley the new name is supposed to be provided by the user. It can be an existing PVC they may have created which uses the new storage class. If it's not an existing PVC, a new PVC by that name will be created.

2021-09-28 17:05 UTC, pranavgaikwad commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +> Approach 1 will only work on "known" workload resources and will not work on workloads managed through a Custom Resource. On the other hand, Approach 2 doesn't make any changes to the original work
@shawn-hurley good idea. As long as, CRs follow the generic Pod Template spec, we can definitely handle those cases. Given our experience with MTC so far, most user workloads have been standard Kubernetes workloads. so documentation is possible.

2021-09-28 17:59 UTC, alaypatel07 reviewed
Thanks for the detailed steps. I think we should Approach 1 feels the most safer and workable, even with its limitation of just working with the known workload APIs

2021-09-29 20:57 UTC, eriknelson requested changes

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +During a state migration, the _MigPlan_ controller will determine whether any of the PVCs are being migrated within the same cluster and in the same namespace. If that's the case, it will raise a _Wa
Thinking about backwards compat -- if the key is not present, what behavior do we want (should match the default I assume).

If it's not present and we want that to indicate to the controller "automatically update the references", then the polarity of the field needs to be something like "do_not_automatically_update", so that `do_not_automatically_update_ref = false` means **do** perform the auto ref update. That gets confusing quickly.

I'm not really advocating for anything here, but I think we want to be explicit about backwards compatibility concerns in any enhancement *any* time we suggest a change to the CRD API.

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 2: Use Indirect Volume Migration
We've been flirting with the idea of moving away from restic entirely for a lot of reasons (it being a daemonset and the consequences that come with that comes to mind). I'm not sure we want to couple ourselves _more_ to restic if that's really the direction we want to be headed.

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 3: Update PVs inplace without changing the user workloads
This approach scares me without a bullet proof fallback should a failure interupt this transaction. The entire swap has to be atomic, else we need to be able to easily rollback.

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 1: Update the user workloads to point to migrated PVCs
I think I actually like this approach the most for a few reasons:
* It feels the safest in that we'd be able to delegate to the user whether or not they want us to clean up the original pvc afer we're done (i.e. delete), or if they want them to be preserved in case they need to rollback.
* This makes me think we might want to support rollback for a conversion that restores the original pvc references. This approach would make it easier to accomplish that.

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +The default behavior is to turn the functionality on whenever PVCs are migrated within the same namespace using _State Transfer_.
Do we have any concern with altering default behavior with minor version increments? Meaning in 1.6 we did not do this by default, and in 1.7, it's possible that by default, we'd have an entirely different behavior that's potentially undesirable. If a user is already familiar with the behavior as of 1.6, the default behavior would come as a surprise with 1.7?

@shawn-hurley I'm interested to hear your thoughts on this question.

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +Any existing resources from previous versions would not have the above annotation set. Thus, the functionality will be turned off for _MigMigration_ resources created in older versions of MTC.
From a semantics perspective, it feels more correct to have conditional behavior be a `spec` field, as in: "I'm a user and I'm expressing my intent for this migration to behave in this manner".

2021-09-29 20:57 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 1: Update the user workloads to point to migrated PVCs
Upon further reading, the issue of this approach only working for "known" workloads feels like it makes this not really an option. Can we elaborate on what is meant by "known" type? If it can't work generically, I'm inclined to take it off the table.

2021-09-29 21:57 UTC, alaypatel07 commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 1: Update the user workloads to point to migrated PVCs
I think by "known" workloads we mean all the popular workloads which have PodTemplate embedded inside. mig-controller already has the logic to read those pod templates and create a stage pod for it. Using the same workflow but editing the pod template to use a migrated PVC is what this approach suggests. Since this already exists, we are not creating the situation any worse by implementing this approach. The unknown workloads would be pods using PVC that are managed by a specific operataor, this approach will break those, but so will be the stage pod logic and quiesce logic.

2021-09-30 00:23 UTC, eriknelson commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 1: Update the user workloads to point to migrated PVCs
> The unknown workloads would be pods using PVC that are managed by a specific operataor, this approach will break those, but so will be the stage pod logic and quiesce logic.

+1, thank you that makes sense, can get this definition / detail added to the document to specify exactly when this breaks down?

I wonder if it would be acceptable to say: "Hey this automatic swap will succeed for traditional workloads that look like $DETAILS, but under this circumstance it is impossible to automatically update the references and you should disable the feature and handle it yourself"

2021-10-04 16:54 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +During a state migration, the _MigPlan_ controller will determine whether any of the PVCs are being migrated within the same cluster and in the same namespace. If that's the case, it will raise a _Wa
I agree this needs to follow two main things.

1. The default value must preserve the old behavior. Say an old resource exists, it should continue to work as defined in that CR does not get new behavior (changing deployments). 
2. That the new field must be optional and the default of the optional needs to conform to 1 above.

2021-10-04 16:57 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +### Approach 1: Update the user workloads to point to migrated PVCs
I wonder if we even want to try and support something that is owned by operator and not a "pod templated controller". 

I can imagine that even the PVC name and storage class could be owned by some other controller in the operator world. I wonder if a "consult your operator if deployment and PVC are owned by the operator" may be the safest guidance?

2021-10-04 17:03 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +The default behavior is to turn the functionality on whenever PVCs are migrated within the same namespace using _State Transfer_.
I think that this is not something that we can do IMO. a resource that works one way on 1.6 should not have radically different behavior on 1.7 IMO.

I think that we *COULD* in some release notes over a couple of versions change the default but I would question if that is really necessary here. 

I think that the UI could set this field by default in 1.7 and that makes sense to me but from an API perspective, I would not want to change this behavior.

2021-10-04 17:04 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +Any existing resources from previous versions would not have the above annotation set. Thus, the functionality will be turned off for _MigMigration_ resources created in older versions of MTC.
+1 the annotation just becomes an un-versioned spec value that we have to handle IMO.

2021-10-18 16:39 UTC, pranavgaikwad commented
@shawn-hurley @sseago @alaypatel07 I moved the alternative approaches we discarded to a different section and addressed concerns around default value of the field. PTAL!

2021-10-18 16:56 UTC, shawn-hurley commented on enhancements/crane-1.x/inplace-storage-conversion/README.md
> +	AutoUpdatePVCRefs bool `json:"autoupdatepvcrefs,omitempty"`
I think I would prefer this to be in a typed field as well

2021-11-09 15:48 UTC, merged