Propose changes to Migration Plan to improve storage conversion experience
konveyor/enhancements pull request #48
Opened 2021-10-04 20:55 UTC by pranavgaikwad

This PR proposes new changes to Migration Plan API to improve UX of Storage conversion.

2021-10-04 21:30 UTC, sseago reviewed
In addition to the earlier question, are these two options going to be exposed via the migplan wizard, or does that UI create "normal" migrations only?

2021-10-04 21:30 UTC, sseago commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +	IsStorageConversion  bool `json:"isStorageConversion,omitempty"`
Is it valid to select both state migration and storage conversion? i.e. are there 3 possible values here ("normal, "state migration", "storage conversion") or four (two independent boolean values)? If there are only 3 values, would it be better to have a "type" field with "normal", "state", and "storage conversion" as valid values?

2021-10-04 21:56 UTC, shawn-hurley reviewed
I am wondering if there is something else that can be done here than adding this field to the API. If I am an API user, I don't think that these fields help me understand what to do and I think that it may cause more confusion, because if I understand correctly if I choose to do some things now my plan will be invalid?

2021-10-04 21:56 UTC, shawn-hurley commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* Based on the type of the migration, we can also enable/disable indirect migration and hooks options. Also, for _State Migration_ we can provide users with further options for configuring permission
Is there a way to infer this from other fields? Is this specifically for the UI to know what to show or are there going to be new validations on the mig migration? I am having trouble understand from an API perspective how these fields help me understand how to do X or Y.

2021-10-05 15:09 UTC, djwhatle commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +	IsStorageConversion  bool `json:"isStorageConversion,omitempty"`
+1 to that Scott. I think an early example of API short-sightedness was introduction of the `isStage` field, which made the API a bit awkward when we later introduced other types of migrations (e.g. Rollback).

Having a type field like you suggest makes sense.

2021-10-05 15:09 UTC, djwhatle commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +These fields will tie every plan to a specific type of migration. The plan cannot be used for a different type of migration once that field is set. The field can only be changed if there are no migra
How will we enforce that a plan cannot be used for different types of migrations later?

2021-10-05 15:11 UTC, djwhatle commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* _Storage conversion_ is already possible in MTC 1.6 but it doesn't have a guided experience. The users need to set the right namespace and PV mappings in the Migration Plan, set the source & destin
At a high level, what in the migplan logic is influenced by changing a migplan to these other types?

2021-10-05 16:45 UTC, pranavgaikwad commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +	IsStorageConversion  bool `json:"isStorageConversion,omitempty"`
@djwhatle @sseago I agree. I thought about having a Typed field, but reconciling existing MigPlans from older versions would be difficult if we introduce a typed field instead of a boolean. So absence of the boolean != absence of the typed field. If we can find a better solution to the problem (perhaps, set default to normal migrations) we should definitely make it a Typed field.

2021-10-05 16:49 UTC, pranavgaikwad commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* Based on the type of the migration, we can also enable/disable indirect migration and hooks options. Also, for _State Migration_ we can provide users with further options for configuring permission
@shawn-hurley Its for UI and backend both. Imagine, in the API, there are various ways the user can configure a MigPlan for storage conversion. Two main examples are - 1. Storage convert by changing the namespace 2. Storage convert by preserving the namespace but changing the PV names. We want to standardize and support only one workflow (we decided to go with no.2). So as soon as the user indicates a "type" of migration the plan will be used for, we will pre-fill rest of the values (setting source and destination cluster to the same, omission of indirect options), the controller will trigger specific validations for Storage Conversion. In future, we will also leverage the intra-cluster State Migration for storage conversion that you worked on (which is based on Service instead of Route)

2021-10-05 18:05 UTC, shawn-hurley commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* Based on the type of the migration, we can also enable/disable indirect migration and hooks options. Also, for _State Migration_ we can provide users with further options for configuring permission
> we will pre-fill rest of the values (setting source and destination cluster to the same, omission of indirect options), the controller will trigger specific validations for Storage Conversion. In future, we will also leverage the intra-cluster State Migration for storage conversion that you worked on (which is based on Service instead of Route)

How does this happen for an API user?

2021-10-05 18:25 UTC, alaypatel07 commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* If the users perform a _State Migration_ by selecting a subset of PVCs in the plan, those settings are persisted on the plan itself. However, that _MigPlan_ is still available for normal migrations
```
For instance, if a PVC is skipped from a state migration, it remains skipped during a final migration as well. But if a workload is using that PVC, it would fail to come up in the destination cluster.
```

Isnt this true for normal migplans as well? if a user selects 1/2 of the pvc for a plan to "stage" it and then runs final migration, they'll have workloads not coming up? so this is an existing problem not just for state migration?

2021-10-05 19:06 UTC, eriknelson requested changes

2021-10-05 19:06 UTC, eriknelson commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +These fields will tie every plan to a specific type of migration. The plan cannot be used for a different type of migration once that field is set. The field can only be changed if there are no migra
+1 I came to ask the same question

2021-10-05 19:10 UTC, sseago commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* If the users perform a _State Migration_ by selecting a subset of PVCs in the plan, those settings are persisted on the plan itself. However, that _MigPlan_ is still available for normal migrations
@alaypatel07 The difference is that at least at one point the regular UI only allowed skip for PVCs that didn't belong to applications -- i.e. not attached to either a running pod or a quiesced Deployment/DC/etc. However, to support state migration I think we opened that up to allow skipping of all PVCs, so yes, if that is the case, this is an issue for regular migration as well.

2021-10-05 19:19 UTC, pranavgaikwad commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* If the users perform a _State Migration_ by selecting a subset of PVCs in the plan, those settings are persisted on the plan itself. However, that _MigPlan_ is still available for normal migrations
@alaypatel07 no its not. For normal migplans, we cannot select PVs.

2021-10-05 19:20 UTC, pranavgaikwad commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> + > 1. This requires exposing previously private resources which contain sensitive
Just template text

2021-10-05 19:52 UTC, sseago commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +* If the users perform a _State Migration_ by selecting a subset of PVCs in the plan, those settings are persisted on the plan itself. However, that _MigPlan_ is still available for normal migrations
@pranavgaikwad at least for PVs that are not bound to pods/deployments, they *can* be selected to skip in the wizard. Also, I thought there was a PR along the way that updated the available actions to include "Skip" for everything, although maybe that didn't get merged?

2021-10-15 15:18 UTC, shawn-hurley commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +This will present some problems with existing _MigMigrations_. Since migrations are supposed to reach to completion, these problems are relatively easier to solve.
what happens if I have a Migration YAML that I keep using? if this field is set to `nil` what is the behavior?

2021-10-15 15:19 UTC, shawn-hurley commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +Existing CRs will not have the type field set, instead they will have the old booleans. In 1.7, we can deprecate the booleans and add controller logic to correctly set the Type field based on the old
+1 this seems like the correct approach, have we considered a validating or mutating admission webhook to do this?

2021-10-15 16:57 UTC, alaypatel07 commented on enhancements/crane-1.x/migplan-ux-improvements/README.md
> +This will present some problems with existing _MigMigrations_. Since migrations are supposed to reach to completion, these problems are relatively easier to solve.
yes, I think that is a valid missing scenario, seems like the best way to handle that would be a webhook. The question is how hard is it to build and maintain webhook? do we want to take that pain given the strategic direction we are heading to? Unfortunately, I do not know the answer to those questions.

2021-10-19 12:53 UTC, merged