adding enhancement for management of custom plugin repositories
konveyor/enhancements pull request #54
Opened 2021-11-23 22:47 UTC by JaydipGabani

This enhancement proposes solutions for:
- Adding/Removing custom crane-plugin repository
- Installing/Uninstalling/Listing plugins from custom crane-plugin repository

2021-11-26 04:14 UTC, djzager reviewed
Thanks for this effort. I think being able to have custom plugin repositories is a great idea but I do wonder if we can support this without adding a bunch of new subcommands we have to support...at leeast we could consider waiting until we know what is painful about managing it manually.

Some general feedback included, I would like the idea of `crane.yaml` to be given more detail before going in for another round of feedback.

2021-11-26 04:14 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `home/user/.conf/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already added on t
`/home/user/.conf/crane.yaml` seems like an odd location, maybe you want to be using `$XDG_CONFIG_HOME` (ie. https://wiki.archlinux.org/title/XDG_Base_Directory ). I could see `$XDG_CONFIG_HOME/crane/config.yaml`.

Has this file been mentioned previously? What relation does this have to:

```
Global Flags:
  -c, --config-file string   Path to config file which contains a yaml representation of cli flags. Explicit flags take precedence over config file values.
```

Can the location of this file be overridden with some analogue to the `KUBECONFIG` (ie `CRANECONFIG`)?

2021-11-26 04:14 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +Instead of maintaining a file we ask users to create such file with the name `crane.yaml` and place it under a specific path with appropriate entries, and we list, add and remove plugins by reading a
This review is the first time I've heard of this `crane.yaml`...has it been implemented already or would it be a part of this effort? Could you provide more detail on this `crane.yaml`...it's relation to the config-file that can be used for individual commands...and what this file will look like?

2021-11-26 04:14 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +  crane plugin-manager list-repo [flags]
Maybe `list-repos`?

2021-11-26 04:14 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +title: neat-enhancement-idea
Should give it an actual title :sunglasses:

2021-11-26 04:14 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `home/user/.conf/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already added on t
Yeah. The way this reads it sounds like something that has to be included with the install of the binary, specifically this part:
> On high level this command will look at a file placed at `home/user/.conf/crane.yaml`

What happens if that file isn't there? Do we create it?

2021-11-28 17:15 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +### User Stories [optional]
:+1:

2021-11-28 17:15 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +We will provide cli commands within `crane plugin-manager` to add and remove any custom plugin repository.
:+1:

2021-11-28 17:15 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +We are proposing two new sub commands under `crane plugin-manager` to manage custom repositories.
:+1:

2021-11-28 17:23 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +title: neat-enhancement-idea
:+1:

2021-11-28 17:23 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +  crane plugin-manager list-repo [flags]
:+1:

2021-11-28 17:25 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +Instead of maintaining a file we ask users to create such file with the name `crane.yaml` and place it under a specific path with appropriate entries, and we list, add and remove plugins by reading a
`crane.yaml` is a config file that contains a map with the key being the name of a plugin-repository (I.e `default`, `my-crane-plugins` etc.) and its value being URL/path of the repository. It is the same file we are maintaining through proposed commands in this enhancement (i.e add-repo. remove-repo). This is a common config file for `crane` rather than a config file containing flag inputs to be consumed by `crane` commands.

2021-11-28 17:28 UTC, JaydipGabani commented
> Thanks for this effort. I think being able to have custom plugin repositories is a great idea but I do wonder if we can support this without adding a bunch of new subcommands we have to support...at leeast we could consider waiting until we know what is painful about managing it manually.
> 
> Some general feedback included, I would like the idea of `crane.yaml` to be given more detail before going in for another round of feedback.

Yeah, I discussed an alternative to adding these subcommands in this enhancement. In this case, one solution that I could think of is that we ask users to create a file with the name `crane.yaml` and place it at `$XDG_CONFIG_HOME/crane/` with appropriate entries, and we list, add and remove plugins by reading all the repos mentioned in the file `$XDG_CONFIG_HOME/crane/crane.yaml`. In this approach there is no need to add any commands, however the responsibility to create an appropriate config file for `crane` to consume lies on the user.

2021-11-28 17:33 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `home/user/.conf/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already added on t
1. No we have not thought of `$XDG_CONFIG_HOME/crane/crane.yaml` before. Its config file for `crane` not for individual commands (i.e with flag `-c, --config-file`). Right now the location of the config file is predetermined which is as you suggested `$XDG_CONFIG_HOME/crane/crane.yaml`, however we can have an option to override with `CRANECONFIG`, if desired.

2. Yeah, if the file is not already present then we create the file

2021-11-30 02:29 UTC, djzager requested changes
Assuming I understand the config file mentioned correctly, I do believe that serious consideration should be given to whether it deserves an enhancement entirely to itself.

I have reservations about the idea that we have a configuration file for the plugin-manager and a separate (optional) configuration file that controls `cranes` behavior, that I think would be best hashed out in it's own PR.

Let me know what you think @JaydipGabani @sseago ... maybe we can chat about this in scrum?

2021-11-30 02:29 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Provide user with sufficient documentation on how to setup custom plugin repositories, how to develop custom plugins and how to properly add/remove custom crane-plugin repository
An example of a mitigation to an existing risk would be validating the user's input before accepting it as a plugin repo.

2021-11-30 02:29 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
My understanding is that this config file (that would probably make more sense as `$XDG_CONFIG_HOME/crane/config.yaml` ...total nitpick) is totally separate from the `--config-file` you would use at the command line. 

Am I understanding this clearly? I'm really concerned that having multiple configuration files that do different things will be incredibly confusing to all parties involved.

If this configuration file is itself a net new idea, I believe it deserves it's own enhancement that we can discuss in depth.

2021-11-30 15:23 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Do we want the user to have the control to override/remove default plugin source?
I think the current env var override for the default source is a workaround for the fact that add/remove plugin repos doesn't exist yet. I think once we have the ability to add custom repos, the way to override the default location would be simply to add the desired one -- possibly also removing the default one, if we allow that). In the crane-runner use case, this would mean adding the *local* plugin repo and removing/disabling the default github-based one.

2021-11-30 15:23 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
So the existing "config file" is really more of a "user input file" -- it (partially or completely) replaces the full set of flags passed into a particular crane invocation. This file is actually storing state *between* crane invocations -- i.e. a repo added in one invocation is available in the next. Maybe instead of config.yaml it should be repos.yaml? Also, since adding/removing plugins is handled by manipulating subdiretories of <plugin-dir>, I think this repositories.yaml file should probably live within the <plugin-dir> itself. <plugin-dir>/repositories.yaml would list the repos, <plugin-dir>/managed/<repo> would contain installed plugins for a given repo, etc.

2021-11-30 15:23 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
Since it's not a general-purpose "configuration file" -- it's really just a list of installed repos in a particular plugin dir, I don't really think it warrants its own enhancement, assuming that its scope is limited to what I proposed above and clearly defined in this enhancement.

2021-11-30 15:23 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Do we want the user to have the control to override/remove default plugin source?
So we can support removing the default repo by adding a bool value to the repos.yaml file in <plugin-dir> (see below for context on this) -- something like `defaultRepoDisabled`, where calling `remove-repo` with the default repo specified would set this bool.

2021-11-30 18:00 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
> So the existing "config file" is really more of a "user input file" -- it (partially or completely) replaces the full set of flags passed into a particular crane invocation. 

So long as we appreciate the potential confusion that is `--config-file ${NOT_REALLY_A_CONFIG_FILE}` :grin: , I'm good.

> This file is actually storing state between crane invocations -- i.e. a repo added in one invocation is available in the next. Maybe instead of config.yaml it should be repos.yaml?

I think calling it `repos.yaml` is a great idea.

> Also, since adding/removing plugins is handled by manipulating subdiretories of , I think this repositories.yaml file should probably live within the itself. /repositories.yaml would list the repos, /managed/ would contain installed plugins for a given repo, etc.

I'm not fully aware of the precedence for this, but having it drop a `repos.yaml` (I like it and I'm sticking with it) in the current working directory eschews convention...right?

Maybe we could use this specifically https://pkg.go.dev/os#UserConfigDir to determine where to place this crane repos configuration file:

`craneRepos := os.UserConfigDir() + "/crane/repos.yaml"`

> I don't really think it warrants its own enhancement

I think that you are right, if this config file is scaled back to only dealing with the configured repositories then it doesn't need it's own. The only caveat I would add is that it does deserve it's own subsection in this enhancement (before digging into the subcommands) to fully describe what it is + where it lives + what it does.

2021-11-30 18:26 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Do we want the user to have the control to override/remove default plugin source?
[Here](https://github.com/konveyor/crane/blob/main/internal/plugin/plugin_manager_helper.go#L142) is the setting to override default source of the plugin repository. Right now there is one source always present. If the env variable is not set then we point to default source that is `konveyor/crane-plugins`.

2021-11-30 18:30 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Provide user with sufficient documentation on how to setup custom plugin repositories, how to develop custom plugins and how to properly add/remove custom crane-plugin repository
In this case, I feel we would need to define what is an acceptable validation of custom plugin repo looks like, 

Do we validate if the path provided is a valid one for repo?

Do we check if the structure of the custom plugin repository is defined as required?

Do we check the content of `index.yml` file and `manifests` and validate the proper format and entries exist there?

2021-11-30 18:53 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Do we want the user to have the control to override/remove default plugin source?
@JaydipGabani I'm thinking that once we have the ability to add repos we can remove this env var. If a user (or crane-runner, as it will need this) needs to override, the right thing to do will be to remove the default and add the custom one.

2021-11-30 18:55 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
@djzager s/current working directory/<plugin-dir>/

2021-11-30 18:55 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
```
Maybe we could use this specifically https://pkg.go.dev/os#UserConfigDir to determine where to place this crane repos configuration file:

```
I don't think this is correct. I think we want this to be the plugin dir that we're explicitly dealing with.

2021-11-30 18:56 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
As for "**NOT_REALLY_A_CONFIG_FILE**" -- do we want to call this flag `--input-file` instead?

2021-11-30 18:57 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +On high level this command will look at a file placed at `$XDG_CONFIG_HOME/crane/crane.yaml`, and add an entry with respective name and URL passed in the command. If passed name or URL is already add
The point is that the list of installed plugins is different based on a different passed-in `--plugin-dir` -- I think the list of installed repos should be similarly modified by that param.

2021-12-01 15:15 UTC, djzager commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Provide user with sufficient documentation on how to setup custom plugin repositories, how to develop custom plugins and how to properly add/remove custom crane-plugin repository
I'm not sure how far we go here. It's more that I do believe the mitigations we list should address the risks. So, if we say:
> If the user doesn't setup the custom plugin repository in the desired manner, the user might face some issues working with `crane plugin-manager`

How are we planning to mitigate this specific risk? We could validate., but how much can we validate? This is the place for you to go into these details about all the validations we could do and the necessary cost/benefit analysis. Once you have that you can say, in the enhancement, what level of validation you think is appropriate based on cost/benefit analysis and reviewers can share their thoughts.

In the end, we have a historical record of this conversation of all the risks/mitigations and relevent cost/benefit analysis to show why we ended with the implementation we decided.

2021-12-01 15:19 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Provide user with sufficient documentation on how to setup custom plugin repositories, how to develop custom plugins and how to properly add/remove custom crane-plugin repository
"how much can we validate" -- so currently we parse the index file for the list action. One possibility is that we could use the same parsing code to validate the passed-in URL on `add-repo` -- if it returns a list of plugins (internally, not for display to the user), then we declare it good. If the action fails, then we error out as "not a valid plugin repo".

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Do we want the user to have the control to override/remove default plugin source?
So based on prior discussion, the "default" plugin source is merely a "crane-plugins" plugin source that we automatically add to the template repos.yaml on creation, which means we can remove, re-add it just like any other plugin repo once created.

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +Along with the our own default plugin-repository, we would like to give the users an option to add their own plugin-repositories from which they can discover, install, and uninstall any custom plugin
Rather than reference the github repo path, reference the actual path that contains the index file: https://raw.githubusercontent.com/konveyor/crane-plugins/crane-cli/index.yml

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +Along with the our own default plugin-repository, we would like to give the users an option to add their own plugin-repositories from which they can discover, install, and uninstall any custom plugin
It's the file content that matters here, not the fact that it's a github repo.

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +The ability to add/remove custom crane-plugin repositories is needed in a restrictive environment where the access to the repository from outside the network is revoked. In such cases, if a user can
"...in a restrictive environment where the access to the repository from outside the network is revoked, as well as for environments where custom plugins not provided in the crane-plugins repo are needed."

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- User should be able to add any custom plugin repository
I'm thinking we remove "custom" here (and below), since they can add/remove *any* plugin repository, custom or provided-by-konveyor.

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- User should be able to discover plugins from custom plugin repository
s/custom/added/

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- User have a custom plugin repository setup in similar manner as [crane-plugin](https://github.com/konveyor/crane-plugins)
Link to the raw index file as above.

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +A config file `repos.yaml`, placed in `--plugin-dir`. This file contains plugin repository name as key and respective URL as value. Absence of this file in a plugin directory would mean crane will on
"Absence of this file in a plugin directory would mean crane would create a new repos.yaml in the plugin directory linking only to the crane-plugins repo."

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +foo: <github raw url for an index.yaml file>
"github raw or other url/local path to an index.yaml file" -- it doesn't need to be on github, and it won't be on github for local repos.

2021-12-01 15:31 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- To update an entry in `repos.yaml`, first the repo needs to be removed(i.e `crane plugin-manager remove-repo foo -p bar`), and then needs to be added with updated path(i.e `crane plugin-manager add
Question: does removing a repo *also* remove the plugins currently installed from that repo?

2021-12-01 15:35 UTC, shawn-hurley requested changes
I think we need to consider some scenarios.

2021-12-01 15:35 UTC, shawn-hurley commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +#### Risks
What other risks are there? do we have upgrade risks how do we handle when the crane CLI is updated and the plugin repo no longer supports the crane CLI version (request/response)?

What about dealing with plugins having the same name? How do we handle naming conflicts? can repos have the same name?

2021-12-01 15:35 UTC, shawn-hurley commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- A validation against a plugin repo that ensures a plugin-repository (that `crane` refers to) is valid.
How are we exposing errors when they occur with a plugin manager and a repo?

2021-12-01 15:41 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +The ability to add/remove custom crane-plugin repositories is needed in a restrictive environment where the access to the repository from outside the network is revoked. In such cases, if a user can
Yeah, I had a similar comment. I think the motivation is probably equally "new/custom repos" and "'new ways of accessing the default one" -- although in terms of content of the enhancement, I think this addition doesn't really change much.

2021-12-01 15:42 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +#### Risks
I think plugin names need to be unique *within a repo* but not across repos. @JaydipGabani is that right?
Repo names must be unique, but they're user-supplied rather than pulled out of the repo url itself.

2021-12-01 16:26 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- To update an entry in `repos.yaml`, first the repo needs to be removed(i.e `crane plugin-manager remove-repo foo -p bar`), and then needs to be added with updated path(i.e `crane plugin-manager add
That is achievable if desired, but do we want this behavior?

2021-12-01 16:29 UTC, sseago commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- To update an entry in `repos.yaml`, first the repo needs to be removed(i.e `crane plugin-manager remove-repo foo -p bar`), and then needs to be added with updated path(i.e `crane plugin-manager add
My concern is if we add a repo, then install a plugin, then remove the repo, then add a new one with the same name, there may be some weirdness if there are plugins from completely different repo sources listed as if they are from the same repo.

2021-12-01 16:29 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +A config file `repos.yaml`, placed in `--plugin-dir`. This file contains plugin repository name as key and respective URL as value. Absence of this file in a plugin directory would mean crane will on
+1

2021-12-01 16:29 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +foo: <github raw url for an index.yaml file>
:+1:

2021-12-01 16:30 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- Provide user with sufficient documentation on how to setup custom plugin repositories, how to develop custom plugins and how to properly add/remove custom crane-plugin repository
> A validation against a plugin repo that ensures a plugin-repository (that `crane` refers to) is valid. Meaning that added custom plugin repository have valid plugin manifests.

I think this validation should do for now :thinking:

2021-12-01 16:35 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +Along with the our own default plugin-repository, we would like to give the users an option to add their own plugin-repositories from which they can discover, install, and uninstall any custom plugin
:+1:

2021-12-01 16:45 UTC, JaydipGabani commented on enhancements/crane-2.0/plugin-management/custom-plugin-repo.md
> +- To update an entry in `repos.yaml`, first the repo needs to be removed(i.e `crane plugin-manager remove-repo foo -p bar`), and then needs to be added with updated path(i.e `crane plugin-manager add
Yeah, removing all the plugins alongside the repo makes sense

2022-02-15 20:22 UTC, shawn-hurley approved these changes
/lgtm sorry for the delay

2023-02-17 18:25 UTC, jwmatthews commented
Due to the nature of Konveyor changing to align to the [Unified Vision](https://github.com/konveyor/enhancements/tree/master/enhancements/unified_experience), I think it's best we close this PR out.

If you feel strongly otherwise please reopen and add a comment.

2023-02-17 18:25 UTC, closed without merging