DVM Permissions Handling
konveyor/enhancements pull request #55
Opened 2021-12-02 14:49 UTC by pranavgaikwad

2021-12-06 14:36 UTC, shawn-hurley requested changes
I am personally worried about adding this set of code to MTC because of the way it could cause issues on regression or a bug. I would like to discuss some other alternatives.

2021-12-06 14:36 UTC, shawn-hurley commented on enhancements/crane-1.x/dvm-permission-handling/README.md
> +## Alternatives
I would like to discuss an alternative that is out of the band of MTC entirely, for instance, a crane 2 command or a set of actions to take as a user in a knowledge base.

2021-12-07 19:09 UTC, alaypatel07 commented on enhancements/crane-1.x/dvm-permission-handling/README.md
> +- The Rsync Server Pod will be forced to use the UID of the destination namespace. To enable that, we will add a new SCC which will be a clone of existing `rsync-anyuid` SCC with some changes. The ch
how do you propose to make this change? I assume this has to be in mig-operator? do we want to add the same thing for legacy-operator or will this feature only be available in newer versions?

2021-12-07 19:11 UTC, alaypatel07 commented on enhancements/crane-1.x/dvm-permission-handling/README.md
> +- The Rsync Server Pod will be forced to use the UID of the destination namespace. To enable that, we will add a new SCC which will be a clone of existing `rsync-anyuid` SCC with some changes. The ch
actually nevermind, I found the answer listed below

2021-12-07 19:12 UTC, alaypatel07 commented on enhancements/crane-1.x/dvm-permission-handling/README.md
> +A new scc `rsync-restricted-uid` will be added to address the needs of this use-case. For the most part, this is a clone of `rsync-anyuid` SCC except following changes:
Can you please elaborate on why a new SCC will be needed and we cant use the `restricted` SCC so future us can refer back?

2022-02-15 17:20 UTC, jwmatthews commented
@pranavgaikwad would you take a look and see if we need to make any other updates to this so we can get it ready to merge?

2022-03-28 19:59 UTC, pranavgaikwad commented
Closing as this is no longer considered.

2022-03-28 19:59 UTC, closed without merging