docs: tekton and crane ui integration
konveyor/enhancements pull request #59
Opened 2022-01-28 22:01 UTC by djzager

2022-01-31 18:55 UTC, djzager commented
cc @jmontleon @JaydipGabani

2022-01-31 20:30 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * The UI could bind the appropriate ClusterTasks in the generated Pipeline
would the UI do this even if the user does not have these permissions?

2022-01-31 20:40 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * The UI could bind the appropriate ClusterTasks in the generated Pipeline
What permissions must a user have to access the Crane UI for a namespace at all?

2022-01-31 20:44 UTC, shawn-hurley requested changes
I think that we should consider some approach for versioning on the cluster tasks.

I also believe that we should use the user's oath in some way to have access to the destination cluster rather an trying to rely on an admin user always being present.

2022-01-31 20:44 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * The UI could generate a Kubeconfig impersonating the current user but
Would the UI have access to the user info, and be able to ask the user to do an OAuth flow and get the user's OAuth token? wouldn't we presumably have this?

2022-01-31 20:44 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +1. Do we want to to execute the `crane-transfer-pvc` ClusterTask for each PVC to
each PVC is my vote, and make it async.

2022-01-31 20:44 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* oc & kubectl - for interacting with cluster resources and/or managing cluster
Doesn't oc and kubectl come with kustomize?

2022-01-31 20:44 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +When the user decides to defer execution of the generated
there is no UI component to do this, and it is on the status of the pipeline not the spec?

2022-01-31 20:44 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +It is important that we treat the ClusterTasks supported by Crane Runner **as
is there some way to version these? a label or annotation?

2022-01-31 20:49 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* oc & kubectl - for interacting with cluster resources and/or managing cluster
being able to run `kustomize init` requires the kustomize binary.

2022-01-31 20:51 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +It is important that we treat the ClusterTasks supported by Crane Runner **as
Annotate them with the container image (crane runner image) that held them? This problem might be related to how do we get the operator to override the `image:` field in the ClusterTasks.

2022-01-31 20:54 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +When the user decides to defer execution of the generated
https://tekton.dev/docs/pipelines/pipelineruns/#pending-pipelineruns It's definitely on the `.spec` of the PipelineRun.

> there is no UI component to do this, 

@mturley and I were talking about how to better support it in the Pipelines UI. I'll update this to include the 3 methods currently supported to move a pending pipelinerun.

2022-02-01 18:28 UTC, mturley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * The UI could generate a Kubeconfig impersonating the current user but
I was asking @spadgett about this, unfortunately the plugin SDK does not let me read the current user's OAuth token, it only gives me functions to call to use it under the hood for k8s resource CRUD. I think we'd have to add a form field to the wizard UI to collect it.

See discussion on Slack: https://coreos.slack.com/archives/C011BL0FEKZ/p1643320736160600

2022-02-01 18:39 UTC, mturley commented
Just to copy here: there are a few properties the UI collects (as designed currently) that I don't see how to map to params on the ClusterTasks here for each PVC here: migration type (from prior discussion it sounds like this may not be relevant) target storage class name, capacity, and a boolean for whether to verify the copy.

Slack discussion: https://coreos.slack.com/archives/C02ELCA262K/p1643662825288189

2022-02-14 20:29 UTC, eriknelson requested changes
Overall I think this is a really thorough enhancement and it satisfies our need to get our design thoughts captured so we can begin the implementation. There are several open questions we should document and in some cases defer to follow-on enhancements. Let's just make sure those are all called out, and I will make sure that we have spikes on the roadmap to get those questions answered. Thank you for this @djzager, I learned a lot with the read.

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +        The namespace from which to export resources.
RC: "The namespace in the source cluster from which"

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +  workspaces:
The workspaces on a ClusterTask are really references that point to definitions that are defined in the pipeline, correct?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: pvc-storage-class-name
Do we want to name this something like `dest-pvc-storage-class-name` to make the parameter self evident that this is your desired target storageclass?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +      default: ""
If no endpoint is specified, what is `transfer-pvc`'s default behavior?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * **ANSWER** We are going to run the `crane-transfer-pvc` for each PVC to be
This may be answered elsewhere in the document but as I'm reading it occurs to me that another question that has to be answered here is: if we run one clustertask per pvc transfer...is the the UI that is responsible for adding N clustertasks, in serial, to the pipeline for each pvc that has been selected?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +The `kubectl-scale-down` ClusterTask is responsible for scaling down the
@pranavgaikwad is this task sufficient to accomplish the abstract idea of "Quiesce"? What does MTC do if they are one-off pods with volumes mounted?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +they require, and how they are to be ordered in Pipelines.
I've gotten far enough to find this answer:

> centers around the Pipelines, for this reason the UI will **not** be
instantiating PipelineRuns with embeded Pipeline specifications.

I wonder if we briefly tease this and link to later in the doc?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +#### Application Migration
RC: We should title this "Stateless Application Migration" to call out the stateless use-case

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +#### Application and State Migration
RC:  I think we want to reframe this for UX purposes as "Stage" and "Cutover" pipelines. It's a pattern that our users are already going to be familiar with that folks are going to be looking for. I think we'll want a direct answer for that.

That probably means just renaming some things here, where the state migration is "Stage" and the "Cutover" migration is the "Final" one.

@pranavgaikwad can you review this and see if there is anything that Stage and Cutover does in MTC that we're missing here that you consider to be critical?

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +For ClusterTasks that require access to the destination cluster, we will use the
RC: I think this is the problem we need to blackbox and have that discussion about @shawn-hurley @djzager.

I think this is a non-goal of this enhancement, but we should call out that this is a difficult problem that needs its own enhancement with the details around how this is going to work in a safe manner for a multi-tenant environment.

2022-02-14 20:29 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +To help mitigate these risks, whatever container image specified for Crane
I think an assertion by the pipeline that these are all fall within acceptable and expected versions and it fails fast and loudly with a specific error would be a good thing to add.

2022-02-14 20:36 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +  workspaces:
Correct. In a Task, workspaces define where the data is located on disk for the individual steps...Tekton's doc say it better than I:

> Tasks specify where a Workspace resides on disk for its Steps. At runtime, a TaskRun provides the specific details of the Volume that is mounted into that Workspace.

https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#workspaces-in-tasks-and-taskruns

I think I tried to answer this in the Glossary under Workspaces. Let me know if I need to give it another go.

2022-02-14 20:40 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +      default: ""
it'll fallback to the `crane` binaries default `nginx-ingress`

2022-02-14 20:52 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* kustomize - for customizing the manifests after `crane apply`.
Yeah. We need it for changing the namespace to wherever we are being run. It has some benefits later but we only **need** it for `kustomize init`.

Updating this for more detail.

2022-02-14 21:01 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * **ANSWER** We are going to run the `crane-transfer-pvc` for each PVC to be
I'd like some input from @alaypatel07 here but I have a few thoughts:

1. The `crane` binary itself should be sufficient for throttling parallel migrations. If you were to run a script with `crane transfer-pvc` for 100 PVCs to be migrated, how should `crane` handle that? Maybe this requires it's own RFE? Once we know how `crane` handles it, we can modify the associated ClusterTask to work inside those confines.
2. `i.e., if they got 4 of the 5 pvcs, they shouldn't have to do everything over again.` it may be worth researching [tekton's retries](https://tekton.dev/vault/pipelines-v0.14.3/pipelines/#using-the-retries-parameter) to see if that's something we should consider. In the scenario that 1 PVC transfer fails, and you re-run the `crane transfer-pvc` wouldn't the amount of work to be done with the 4 previously successful transfers be minimal? Or is the concern here failures outside of `rsync` (ie. routes, tunnels, etc)?
3. The UI is responsible for adding a step to the pipeline **for each** pvc to be transferred.

2022-02-14 21:25 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +To help mitigate these risks, whatever container image specified for Crane
could you expand on this?

2022-02-14 21:50 UTC, mturley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * The UI could bind the appropriate ClusterTasks in the generated Pipeline
This is a good question. Currently I have it set up so anyone who can see the developer perspective of the console (everyone?) can access it for any namespace they can see. There is a mechanism to limit this in the plugin SDK that I haven't explored yet.

2022-02-15 13:14 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* The ClusterTasks provided by Crane Runner should still be consumable via
sorry a bit rusty on getting back bear with me a little...

Is this for allowing the users to mix and match the ClusterTasks? for example a user wants to have their own quiesce mechanism for their app?

Do we expect the user to provide a custom crane-runner image with their tasks or do we expect the user to create those tasks in the destination kube server themselves? 

I wonder if a little more explanation on this goal would be good for the record books

2022-02-15 14:00 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +Crane Runner will publish and support a container image including the following
question: when supporting a container image with these binaries, have we thought about how we are going to get the version/commit info back when debugging? I think it was an afterthought with MTC we might want to start thinking about it from the ground up maybe file an RFE if there isn't one?

2022-02-15 14:21 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +The `crane-kubeconfig-generator` ClusterTask is responsible for taking a secret
Is there a way we can store the token in something like a vault instance?

My hope is to use something tighter to store the tokens than kube secrets. If this is possible I think it will kill two birds, i.e. increase security and solve the problems of passing the destination token to cluster tasks

2022-02-15 15:09 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* The ClusterTasks provided by Crane Runner should still be consumable via
This is so users can consume our ClusterTasks in their own pipelines. The UI won't be doing anything to support custom ClusterTasks (at least that's not what's being proposed here).

2022-02-15 15:11 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +Crane Runner will publish and support a container image including the following
I think we should open a Jira to tackle that. Being able to id the container image that provided all the things (ClusterTasks, `crane` and other binaries) is as far as I want to go in this enhancement. Including build info in the crane-runner image is outside the scope of this enhancement imo.

2022-02-15 15:47 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * **ANSWER** We are going to run the `crane-transfer-pvc` for each PVC to be
Had a conversation with @djzager on this, we think the biggest question to be answered, that also considers @eriknelson's points is "how granular do we want to get with the control of parallelization with state-transfer?"

If we want to be in charge of all the decisions, I think it would make sense to put this in transfer-pvc sub-command, this will be more work, like it would need the typed config feature to pass the data to transfer-pvc

If we are okay to loose some control we can let tekton run things in parallel

2022-02-15 16:59 UTC, mturley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
What storage class is used if `dest-pvc-storage-class-name` is left blank? In the UI we make the user choose a destination storage class for each PVC, and I was going to look into how we should determine the default selection there. Maybe there should be some way in the UI for the user to indicate "this is blank, use whatever Crane wants to use".

Also, I imagine this `crane-transfer-pvc` ClusterTask is where we'd need to add params for the capacity of the new PVC and the flag for whether to verify the copy, assuming we still want to collect those in the UI.

2022-02-15 17:44 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +* The ClusterTasks provided by Crane Runner should still be consumable via
@alaypatel07 one of the benefits of using Tekton is the ability to easily customize pipelines with your own tasks. The MTRHO UI experience will take an opinionated approach by building the basic pipeline that helps you run crane tasks in a controlled manner. I.E. a "Stage" and "Cutover" pipeline, that are really an abstraction over the sequence of crane tasks necessary to achieve that type of migration. Naturally for the same reason you might want a hook in MTC, you could hook in another task into the generated pipeline anywhere you'd like. Similarly, you could swap out our quiesce task that scales down for something more sophisticated like pushing a db in to read only mode to retain uptime.

We had these same conversations with MTC, and in practice nobody ever got more sophisticated in this manner with the downstream produce. I would be surprised if that happened here, but at the same time, we also had more sophisticated customers that were using MTC as a building block to accomplish complex orchestrations, so it's not out of the question.

If nothing else, these types of flexibility are tremendously valuable for *us* when we're on the hook supporting migrations. We need the escape hatches that allow us to do the things we need to do in a way that early monolithic MTC (CAM) didn't allow for.

2022-02-15 17:48 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +Crane Runner will publish and support a container image including the following
This is critical for jumpstarting debugging. We have to be able to tie an image in a customer environment back to the upstream commit that has those assets. In the past we just solved this with an image label that has the upstream commit SHA that it was built from. I will file a Spike for this, although I'm not sure it's a problem that's broad enough to warrant its own enhancement. Probably a decision documented on the Jira would do fine, since there is precedent for this. I would just ask the question of whether or not the commit SHA of crane-runner is enough for us, or if we need to include anything else.

2022-02-15 17:53 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +  workspaces:
This is good! Was mostly for my own edification.

2022-02-15 18:41 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +Crane Runner will publish and support a container image including the following
Yeah. I was under the impression that downstream pipelines already placed this type of build info as labels on the published container image. My guess for the goal of the Jira would be to support something like:

```
docker pull ${CRANE_RUNNER_IMAGE}
docker inspect --format='{{ index .Config.Labels "vcs-ref" }}' ${CRANE_RUNNER_IMAGE}
```

2022-02-15 19:21 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +PipelineRun are very difficult to discover or manage -- for this reason the
s/PipelineRun/Pipeline?

2022-02-15 19:23 UTC, alaypatel07 commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +When the user decides to defer execution of the generated
yeah, this one is a little weirdly named, maybe it should have been the "spec.pause" field IMO to stay consistent with other upstream APIs

2022-02-15 20:33 UTC, shawn-hurley approved these changes
looks good

2022-02-15 21:34 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   a PipelineRun out of "PipelineRunPending"?
https://github.com/openshift/console/issues/11060

2022-02-15 21:39 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +The `crane-kubeconfig-generator` ClusterTask is responsible for taking a secret
Adding this to the open questions with link to relevant Jira once it exists :sunglasses:

2022-02-16 00:54 UTC, alaypatel07 reviewed
Thanks for the thorough write up, overall it makes a lot of sense.

/lgtm

2022-02-16 02:40 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
Storage class name is optional so it shouldn't be required by our ClusterTask or `crane`. I'm uncertain if the UI should require this -- I am not fully aware of the behavior when left blank -- and would defer to @shawn-hurley or @eriknelson. Maybe leaving it as `""` should be acceptable?

After talking with @alaypatel07 I'm not certain what priority we should give to "verify the copy". I feel like we at least need namespace, size, storageClassName and I'm iffy on accessModes, changing the PVC name, and this verify copy.

2022-02-16 02:43 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +Crane Runner will publish and support a container image including the following
https://github.com/konveyor/crane-runner/issues/33 since I couldn't figure out how to word a Jira.

2022-02-16 02:45 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +        The source cluster namespace in which pvc is synced.
Unintentional.

It was a mistake to not include these parameters in the pipeline/pipelineRun somewhere. Need to address this piece before this can be called done.

2022-02-16 07:28 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
updated https://issues.redhat.com/browse/MIG-1074 as this will really need to be handled there (with updates to transfer-pvc and crane-runner's ClusterTasks).

2022-02-16 07:31 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +   * **ANSWER** We are going to run the `crane-transfer-pvc` for each PVC to be
We have a whole spike dedicated to researching this question https://issues.redhat.com/browse/MIG-1082 , we also have the bug in crane https://github.com/konveyor/crane/issues/66 .

All of this is documented in the enhancement. I consider this resolved.

2022-02-16 13:58 UTC, eriknelson commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
> I am not fully aware of the behavior when left blank -- and would defer to @shawn-hurley or @eriknelson. Maybe leaving it as "" should be acceptable?

I need to brush off the recent conversation we had @mturley in MTC about its behavior, I think we want to replicate that here.

IMO, if the key is present but explicitly set to "", that feels like a deliberate setting of "None", i.e. no storageclass. I'm trying to recall if that is even something that's meaningful, or what the use-case is for that. If the key is missing, then that feels like it should implicitly fall back to the default storageclass. @djzager I'm unsure if the distinction is even possible with the Tekton params API, or if it will all appear to be "" when read.

"verify copy" is very important. I'm not sure it's MVP, but the reason is that in a regulated industry, this is sometimes an audit requirement. Meaning if we *dont* have this, it will exclude entire classes of users from this tool even being an option to them for usage, and we do have several customers who need this.

It should be relatively simple to pass through to the transfer-pvc command as a switch; we know crane-lib supports it because MTC is using it. I think we should strive to have this for GA.

In early versions of MTC we did not have PVC name mapping and it was heavily requested. I'm struggling to come up with the use-case for needing to have the ability to adjust the accessMode. @pranavgaikwad @sseago do you see either of these being a high priority so that they should be on the critical path for MTRHO GA?

2022-02-16 14:21 UTC, shawn-hurley commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
Adjusting the access mode in this context, I think, is something that we should be worried about doing. 

There is currently no way in RBAC to deny this, *but* it is considered a security risk attempting to be fixed.

Even if there is a use case, I will vote that in a namespace admin copy, we don't allow this.

2022-02-16 14:57 UTC, djzager commented on enhancements/crane-2.0/tekton-ui-integration/README.md
> +    - name: dest-pvc-storage-class-name
> IMO, if the key is present but explicitly set to "", that feels like a deliberate setting of "None", i.e. no storageclass. I'm trying to recall if that is even something that's meaningful, or what the use-case is for that. If the key is missing, then that feels like it should implicitly fall back to the default storageclass. @djzager I'm unsure if the distinction is even possible with the Tekton params API, or if it will all appear to be "" when read.

@eriknelson from a Tekton perspective, it is possible to require it be specified (ie. no default) and that would allow for "" to be explicit.

> Adjusting the access mode in this context, I think, is something that we should be worried about doing.

eek. yeah. After chatting with @alaypatel07 and getting more info, I think https://issues.redhat.com/browse/MIG-1074 is the best place to make final decisions on which flags we are going to add for MVP/GA and address it's impact on crane-runner/crane UI. I linked to this thread from the issue to provide appropriate context to whoever goes to implement the new flags. Let me know if we need any more info.

2022-02-17 13:32 UTC, eriknelson approved these changes

2022-02-17 16:59 UTC, merged