Crane permission change
konveyor/enhancements pull request #63
Opened 2022-03-28 19:58 UTC by pranavgaikwad

2022-03-29 03:03 UTC, shawn-hurley commented on enhancements/crane-2.0/permission-change/README.md
> +A ClusterTask will run an Ansible Playbook to change ownership of files. The job of the ClusterTask is to simply run the playbook and pass variables to it. The actual ownership change will be handled
Why an ansible playbook and not like a POSIX script?

2022-03-29 13:00 UTC, pranavgaikwad commented on enhancements/crane-2.0/permission-change/README.md
> +A ClusterTask will run an Ansible Playbook to change ownership of files. The job of the ClusterTask is to simply run the playbook and pass variables to it. The actual ownership change will be handled
@shawn-hurley Ansible k8s makes it much easier to discover PVCs, read annotations, template the Pod definition (Pod definition will be dynamic based on PVCs in the namespace)

2022-03-29 17:00 UTC, pranavgaikwad commented on enhancements/crane-2.0/permission-change/README.md
> +A ClusterTask will run an Ansible Playbook to change ownership of files. The job of the ClusterTask is to simply run the playbook and pass variables to it. The actual ownership change will be handled
@shawn-hurley It could be. Fixing permissions will work at a namespace level (it would be inefficient to launch pod per PVC). On the other hand, transfer-pvc works at PVC level. I felt there was a disconnect there. Apart from that, I think it definitely can be a subcommand.

2022-03-29 18:54 UTC, shawn-hurley commented on enhancements/crane-2.0/permission-change/README.md
> +A ClusterTask will run an Ansible Playbook to change ownership of files. The job of the ClusterTask is to simply run the playbook and pass variables to it. The actual ownership change will be handled
I think I am asking why we are bringing in a whole new technology that someone would have to have to run the full workflow from a CLI.

2022-04-05 20:21 UTC, pranavgaikwad commented
> Have we explored the possibility of running rsyncd with a different uid/gid?
> 
> The idea is to not run rsyncd as root user but normal user in the namespace and assume rsyncd read and write access to PVC.
> 
> This would get rid of the original problem of workloads breaking when uid/gid has changed.
> 
> Attaching reference where I was reading about uid/gid in rsyncd conf file for quick access
> 
> ```
> uid
> This parameter specifies the user name or user ID that file transfers to and from that module should take place as when the daemon was run as root. In combination with the lqgidrq parameter this determines what file permissions are available. The default is uid -2, which is normally the user lqnobodyrq.
> gid
> This parameter specifies the group name or group ID that file transfers to and from that module should take place as when the daemon was run as root. This complements the lquidrq parameter. The default is gid -2, which is normally the group lqnobodyrq.
> ```
> 
> https://linux.die.net/man/5/rsyncd.conf

@alaypatel07 Using the `uid` `gid` options in Rsyncd has an issue. The owner/group of the root directory of the volume mount are derived from the UID/GID accessible to the Container process. The containers UID/GID depend on SecurityContext of the Pod and/or SCC. Therefore, in order for Rsync daemon uid/gid thing to work, the volume mount must be accessible to that uid/gid. Which implies that the Container process should start with that UID and the UID should belong to that GID. This is only possible when we create a custom SCC that allows that. Without the custom SCC, it won't work in OpenShift. For Kubernetes, it may be possible simply by updating the Container definition. I will do some research on that.

2022-04-12 17:26 UTC, djzager reviewed
I prefer solution 1 knowing that we _could_ support both. My only concern is with non-admin state migrations, if it's possible, what architecture changes may need to be made to support it, and how those changes might affect this work.

With respect to what is in this PR, my vote is for solution 1 and we can pursue solution 2 if there is a need/requirement/want.

2022-04-12 17:26 UTC, djzager commented on enhancements/crane-2.0/permission-change/README.md
> +
I like that we have a way to handle it in the UI seamlessly.

2022-04-12 17:26 UTC, djzager commented on enhancements/crane-2.0/permission-change/README.md
> +### Solution 1: Change ownership of files during state transfer
My preference is for this solution personally. Via the command-line or clustertasks the user should be able to skip this part. In the UI case, I think we should be opinionated about this and just do it for them.

2022-04-12 17:28 UTC, jmontleon commented on enhancements/crane-2.0/permission-change/README.md
> +### Solution 1: Change ownership of files during state transfer
I like Solution 1 as well. I think this should be strongly preferred.

The only reason I would advocate for maintaining Solution 2 is the case where someone performs a migration and only then realizes they  need to fix permissions. Being able to do so after the fact would be very helpful.

2022-04-12 20:30 UTC, pranavgaikwad commented
> I prefer solution 1 knowing that we _could_ support both. My only concern is with non-admin state migrations, if it's possible, what architecture changes may need to be made to support it, and how those changes might affect this work.
> 
> With respect to what is in this PR, my vote is for solution 1 and we can pursue solution 2 if there is a need/requirement/want.

For non-admin, on OpenShift, it means being able to run Rsync daemon with `restricted` UID. @alaypatel07 and I discussed this and I think there is a way to achieve that.

2022-04-13 13:04 UTC, shawn-hurley commented
+1 on solution 1 as long as it does not require any extra SCC

2022-04-18 16:59 UTC, djzager requested changes
Looking great. Some clarity on our approach and I think it's ready to go.

2022-04-18 16:59 UTC, djzager commented on enhancements/crane-2.0/ownership-change/README.md
> +By default, the Rsync Pods will run with minimum capabilties. They will drop `SETGID`, `SETUID`, `KILL` and `MKNOD`:
For me, it would really help me if this were more explicit. Are we creating a custom SCC, if we are, who is creating it and when? **OR** maybe this is handled in the Pod definition itself. It's somewhat ambiguous now how all these pieces come together to work for non-admin users.

2022-04-18 16:59 UTC, djzager commented on enhancements/crane-2.0/ownership-change/README.md
> +Rsync Daemon Pod will not run as `root` user by default. Therefore, `uid`, `gid` fields from Rsync Daemon Pod's configuration will be removed:
These paragraphs make me think that it all has to do with the Pod definition and making it "admissible" on OpenShift/Kubernetes clusters, is that right?

Explaining what we will do more directly would help me better understand.

2022-04-18 16:59 UTC, djzager commented on enhancements/crane-2.0/ownership-change/README.md
> +Rsync Daemon Pod will not run as `root` user by default. Therefore, `uid`, `gid` fields from Rsync Daemon Pod's configuration will be removed:
The portion about Kubernetes, as I understand it the less we ask for in the Pod, the more likely it is to be accepted in clusters with restricted PodSecurityPolicy/PodSecurityAdmission...is that right? That sounds reasonable to me. Is this something we would be able to detect in `crane` and error out appropriately?

2022-04-18 17:11 UTC, pranavgaikwad commented on enhancements/crane-2.0/ownership-change/README.md
> +By default, the Rsync Pods will run with minimum capabilties. They will drop `SETGID`, `SETUID`, `KILL` and `MKNOD`:
@djzager We are not creating a custom SCC. We are simply updating the SecurityContext of Rsync containers and dropping capabilities that require privileges. On OpenShift we expect that the Pods will be admitted via `restricted` SCC which exists by default. On Kubernetes, we expect an equivalent of `restricted` SCC as a PodSecurityPolicy which will admit the Rsync Pods.

2022-04-18 17:17 UTC, pranavgaikwad commented on enhancements/crane-2.0/ownership-change/README.md
> +Rsync Daemon Pod will not run as `root` user by default. Therefore, `uid`, `gid` fields from Rsync Daemon Pod's configuration will be removed:
@djzager It may be possible to detect that based on error strings. At the time of implementation, I will see if there's a more sophisticated way to do it.

2022-04-18 17:23 UTC, pranavgaikwad commented on enhancements/crane-2.0/ownership-change/README.md
> +- we do not need a separate SCC. pods will be admitted via existing admission policies of the cluster (SCC/PodSecurityPolicy/PodSecurityAdmission)
@djzager hope this helps answers your questions

2022-04-18 19:28 UTC, djzager approved these changes

2022-04-19 01:45 UTC, alaypatel07 commented on enhancements/crane-2.0/ownership-change/README.md
> +Rsync Daemon Pod will not run as `root` user by default. Therefore, `uid`, `gid` fields from Rsync Daemon Pod's configuration will be removed:
I think you will get Forbidden http error and then run error string detection.  If no SCC/PSP/PSA is found that admits the pod, an example error from upstream documentation

> Error from server (Forbidden): error when creating "STDIN": pods "privileged" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

https://kubernetes.io/docs/concepts/security/pod-security-policy/

Regardless I think the more important thing to call out is, the Pod API will be our primary way knob of determining the least privileged admission mechanism. 

In order to make this solution robust, we need to find a way to make the SecurityContext configurable for advanced users who need to run with more privileges and they have to coordinate with admin to craft the right SCC at cluster level. In other words, advanced use cases will be solved by documentation and CLI overrides but the generic case will be the most restrictive SCC.

Also, it is my understanding, the list of dropCapabilities is for the `restricted` SCC it might be different in different Cluster environments, but it is reasonable to start with the mentioned default list and change it in the future, assuming it is trivial to do so

2022-04-19 01:51 UTC, alaypatel07 commented on enhancements/crane-2.0/ownership-change/README.md
> +We are only relying on SecurityContext fields to ensure right SCC / PodSecurityPolicies are attached. It is possible that the environments may have multiple conflicting SCC / PodSecurityPolicies and
+1 on calling it out. 

I wonder, if such SCC exists at the cluster level, other services will run into it as well and will be a more generic problem than transfer-pvc failing, but unsure until we get a concrete example.

2022-04-19 02:10 UTC, alaypatel07 commented on enhancements/crane-2.0/ownership-change/README.md
> +By fixing ownership during Rsync transfers ensures that the total time it takes to fix ownership is overlapped with rsync transfer time. In case of Staging/Cutover setting, this time is also spread a
How does this change with the proposed workflow?

2022-04-19 03:15 UTC, alaypatel07 commented on enhancements/crane-2.0/ownership-change/README.md
> +- for shared storages such as NFS or in-tree storages that do not explicitely change the permissions
One this to explicitely call out:

Assume that users want to migrate to shared storage where uid should be as selected in the range, but GID should be 5555 for example, the user could create a custom SCC to allow for this and override uid/gid. This will create the files with right uid/gid but require admin privilege which is a acceptable solution since the storage is shared IMHO

2022-04-19 03:16 UTC, alaypatel07 approved these changes
/lgtm

This covers all the scenarios I had in mind and allows for advanced user options through CLI overrides and documentation.

2022-04-19 11:36 UTC, pranavgaikwad commented on enhancements/crane-2.0/ownership-change/README.md
> +By fixing ownership during Rsync transfers ensures that the total time it takes to fix ownership is overlapped with rsync transfer time. In case of Staging/Cutover setting, this time is also spread a
The point I am trying to make here is that we do not need to run chown explicitely after transfer. The total time overlaps with Rsync transfer time with proposed workflow.

2022-04-19 11:36 UTC, merged