Propose quiesce subcommand in crane
konveyor/enhancements pull request #68
Opened 2022-05-09 18:01 UTC by pranavgaikwad

2022-05-10 22:22 UTC, shawn-hurley requested changes
I am not personally convinced that this is needed, that it is the right thing, or that it would fit into the philosophy of sharp tools. 

Can you write out, today, what the User experience is for this and then what the user experience would be after the fact.

I am concerned about calling this anything other than "scale" or something similar.

2022-05-10 22:22 UTC, shawn-hurley commented on enhancements/crane-2.0/quiesce-workloads/README.md
> +- Enable first class cutover migration flow for Crane CLI users
What are the steps that the crane CLI does for this now?

2022-05-10 22:22 UTC, shawn-hurley commented on enhancements/crane-2.0/quiesce-workloads/README.md
> +- Enable quiescing of DaemonSet resources which is currently not possible using `kubectl`
This is by design right? how do we know whatever we do is safe for the user's workload?

2022-05-13 13:20 UTC, pranavgaikwad commented
After discussion with @alaypatel07 @djzager @eriknelson @shawn-hurley we are rejecting this enhancement. Highlights from the discussion:
- Quiescing applications correctly depends on the nature of the application. It is a problem that cannot be reliably solved with a subcommand. The "quiesce" subcommand will only work for best cases and will leave room for hard to solve corner cases.
- Crane is meant to be a collection of sharp tools which works flawlessly for anything Kubernetes. The quiesce subcommand will only work on a very small subset of workload resources in Kubernetes. It doesn't fit into the philosophy of sharp tools. 
- Implementing a subcommand like quiesce in Crane gives users a false hope that it will intelligently quiesce their applications. It is not true. Quiesce subcommand discussed in this enhancement is not intelligent. It is simply taking resource replicas down.

Conclusion: 
- Merge this enhancement as "rejected"
- Work on a follow up enhancement PR which describes a potential "scale" subcommand  instead. It will simply attempt to scale down the resources. The enhancement will compare the user experience of scale command and compare it with equivalent bash scripts that achieve the same result.

2022-05-13 13:41 UTC, djzager approved these changes

2022-05-13 14:10 UTC, shawn-hurley approved these changes
Thanks for the discussion and for summary.

2022-05-13 14:43 UTC, merged