Enhancement: Run KRM function from Crane
konveyor/enhancements pull request #72
Opened 2022-06-22 23:04 UTC by MundraAnkur

2022-06-23 16:24 UTC, djzager commented on enhancements/crane-2.0/run-functions/README.md
> +> Path to the local directory containing resources. Defaults to the current working directory.
This would probably work on the `--export-dir` like you see from `crane transform`

2022-06-23 16:24 UTC, djzager commented on enhancements/crane-2.0/run-functions/README.md
> +		<OUT_DIR_PATH>: output resources are written to provided directory.
In keeping with `crane`'s philosophy, I believe that we want to *avoid* modifying files in place. We should create a new output directory to hold the results.

2022-06-23 17:08 UTC, pranavgaikwad requested changes
@MundraAnkur Great work! Overall looks good, I have some questions (mostly for my own understanding)

2022-06-23 17:32 UTC, shubham-pampattiwar commented on enhancements/crane-2.0/run-functions/README.md
> +  - "@spampatt"
NIT: @spampatt <-> @shubham-pampattiwar :)

2022-06-23 17:49 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +> Path to the local directory containing resources. Defaults to the current working directory.
So, the default should be an export directory, and instead of mentioning `DIR` in command, we can utilize it under flag **--export-dir**?

2022-06-23 18:23 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +As a crane user, I would like to run KRM functions **without** the crane cli subcommand, such that the given function is applied against the input resources and produces the transformed output.
So, we don't have to depend on cli commands to run the functions.  We can have a module where we pass in some kind of configuration file containing the resource directory, all the functions that we want to run, and any additional arguments that are needed for each function to run.

```
apiVersion: v1
kind: FunctionConfig
metadata:
  name: fn-config1
spec:
  input-resource-dir: testdata/
  functions:
    - image: quay.io/fnproject/fn-test-utils:latest
      env:
        FN_TEST_ENV: fn-test-env
        FN_TEST_ENV_2: fn-test-env-2
      mount:
        - type: bind
          src: path/to/fn-test-utils
          dst: /fn-test-utils
          readOnly: true
    - image: set-namespace:v0.2
      network: true
      data:
          namespace: guestbook
  output-resource-dir: testdata/transform/
```
Something like this can be passed to a function and it will execute the functions and store the transformed resources.

2022-06-23 18:31 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +crane fn run [DIR] [flags] [-- args]
@pranavgaikwad  @shubham-pampattiwar  I'm not really sure what the correct answer to your questions is but I guess initially we are trying to have a capability in the crane to handle KRM functions later we can expand this to utilize KRM functions internally in the subcommands.
 @djzager might be able to answer this more accurately

2022-06-23 19:07 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +	  --as-current-user:
The flag is used to indicate whether the docker/podman container should use the uid and gid that run the command and if it is not specified container will run as "nobody"

2022-06-23 19:18 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +- Alternative to creating an integrated solution to crane cli, we can leverage the already built solutions that provide similar functionality like [KPT](https://github.com/GoogleContainerTools/kpt) a
Actually, I'm not really sure why the alternative solution will not work cos, eventually, we are transforming resources in the local directory by applying functions and that can be done with the existing solution `kpt | kustomize`. 
The only thing that comes to my mind is when we want to use the functions internally without the cli commands, we need to have our own solution which will help us run functions in the pipeline without external help.

2022-06-23 23:30 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +- We will add a subcommand in the crane cli that can run KRM functions with the arguments. The underlying functionality can be built on top of [kyaml](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml)
I am starting to get a little confused on the proposal. 

What is the purpose of the library that we would build? how would you automat something without using the CLI's? are you suggesting that someone builds a binary to run specific KRM functions?

2022-06-23 23:32 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +	  --image, i: (required)
why not just make this a positional arg? if I always have to have it adding `-i` could become tiresome.

2022-06-23 23:33 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +		If enabled, container functions are allowed to access network.
is this an option in the library already?

2022-06-23 23:35 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +As a crane user, I would like to run KRM functions **without** the crane cli subcommand, such that the given function is applied against the input resources and produces the transformed output.
I think that we need to flesh this story out some more, what does the user do?

2022-06-23 23:38 UTC, shawn-hurley requested changes
I think that some of the user stories make sense.


I would also like to discuss if we want to expose some options like network or as-current-user. I am not clear that these are needed and a justification or a use case for them might be helpful IMO.

2022-06-23 23:38 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +- Alternative to creating an integrated solution to crane cli, we can leverage the already built solutions that provide similar functionality like [KPT](https://github.com/GoogleContainerTools/kpt) a
It would be nice to more fully flesh that alternative out. what would a user do while using a combination of crane/kpt/kustomize?

2022-06-24 01:20 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +		If enabled, container functions are allowed to access network.
Yes, it's an option in the [library](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.13.7/fn/runtime/runtimeutil#ContainerSpec)

2022-06-24 01:24 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +	  --image, i: (required)
Yeah, we can make it a positional arg.
If we support binaries in the future then it will be an optional arg

2022-06-24 01:34 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +>	Arguments to pass to the function. The value can be in `key=value` format and come after the separator **'--'**
arg: app=todolist stage=production (set these labels)
crane fn run -i docker.io/example.com/set-labels:v0.1 -- **app=todolist stage=production**

2022-06-24 01:47 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +- We will add a subcommand in the crane cli that can run KRM functions with the arguments. The underlying functionality can be built on top of [kyaml](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml)
As I have mentioned [here](https://github.com/konveyor/enhancements/pull/72#discussion_r905335070), let's say we want to execute some predefined set of functions internally (for ex: when `crane transform` is executed, we have to some basic transformation tasks which are fixed e.g. clean-metadata, remove status, etc), we won't have to separately run `crane fn run clean-metadata: latest`, `crane fn run remove-status: latest` 

The library won't have any special functionality, it's just the same piece of logic that will additionally parse the config file containing functions and necessary details and execute them.

2022-06-24 13:28 UTC, MundraAnkur commented on enhancements/crane-2.0/run-functions/README.md
> +- Alternative to creating an integrated solution to crane cli, we can leverage the already built solutions that provide similar functionality like [KPT](https://github.com/GoogleContainerTools/kpt) a
If we are not running the functions under some other commands (e.g. `crane transform`) internally then all we need to do is run functions on the resources present locally and transform them.

Scenario:
1. User export the resources using `crane export`, then 
2. User transform the resources with `kpt | kustomize`  and store them in the transform directory, finally
3. User applies the transformed resources to the target using `crane apply`

**Let's discuss this and the proposal for a library(maybe just a few methods) to fill the gap in my understanding**

2022-06-27 18:20 UTC, shawn-hurley commented on enhancements/crane-2.0/run-functions/README.md
> +>	Arguments to pass to the function. The value can be in `key=value` format and come after the separator **'--'**
hmm I think we have prior art here @sseago what is the current way we do this

2022-06-27 18:37 UTC, sseago commented on enhancements/crane-2.0/run-functions/README.md
> +>	Arguments to pass to the function. The value can be in `key=value` format and come after the separator **'--'**
@shawn-hurley so we currently have a way to pass args from the CLI to binary (and internal plugins -- basically anything implementing the Plugin interface). If we want to make use of that, we just need to work out a way to implement a KRMPlugin type that's analogous to the BinaryPlugin type -- then we'd get all the arg-passing from CLI for free.

2022-06-28 18:09 UTC, djzager commented on enhancements/crane-2.0/run-functions/README.md
> + 3. User applies the transformed resources to the target using `crane apply`
:grin: `crane apply` only takes json patches (from `crane transform`) and "apply"s those patches to the original manifests (from `crane export`) to give you new manifests that could be `kubectl apply`ed to another cluster.

In this proposed alternative, `crane` would only be useful for the resource discovery piece (or `crane export`), and the rest would need to be handled with `kpt | kustomize`.

2022-06-29 12:31 UTC, djzager reviewed
All of my concerns have been addressed. I'll leave the `lgtm` to others who have requested changes.

Thank you for your efforts.

2022-07-26 13:49 UTC, pranavgaikwad approved these changes
/lgtm

2022-07-26 13:49 UTC, merged