Proposal to create a KRM Function Manager
konveyor/enhancements pull request #73
Opened 2022-06-23 14:33 UTC by JonahSussman

2022-06-23 17:48 UTC, shubham-pampattiwar commented on enhancements/common/krm-function-manager.md
> +This enhancement proposes a new tool, called **Kaffine** to help manage the discovery, installation, removal, and updating of KRM functions. The tool acts as a buffer between the low-level management
+1 on the name `Kaffine` ;)

2022-06-23 17:51 UTC, shubham-pampattiwar commented on enhancements/common/krm-function-manager.md
> +1. **Dependant on container technology**: While KRM functions utilize container technology for now, if that requirement is ever relaxed to include raw binaries, relying on tags will simply not work.
+1 on this motivation point

2022-06-23 18:00 UTC, pranavgaikwad reviewed
I like the idea a lot. Good job on putting this all together. Great enhancement!
 
Before commenting on details, I want to make sure I understand the purpose of this tool: 
1. How does this tool relate to Crane? and potential Crane KRM function runner? 
2. If a separate tool is to built, I believe the best place it belongs to is upstream Kubernetes community. Am I wrong or you already planning to propose upstram?

2022-06-23 18:19 UTC, JonahSussman commented on enhancements/common/krm-function-manager.md
> +1. **Lack of reproducibility**: A developer using `latest` might start out with `v1` on their system. However, when they go to deploy on a different system, `latest` might pull a higher version with
That's correct. However, let's say that `v2` comes out with enhanced bug fixes and the developer uses a tool that [structures their function calls similar to KPT](https://kpt.dev/book/04-using-functions/01-declarative-function-execution). One function might be called multiple times in many different locations, each with its own `v1` tag, leading to a refactoring headache. The problem gets compounded the more a particular function is used.

2022-06-23 18:27 UTC, shubham-pampattiwar commented on enhancements/common/krm-function-manager.md
> +1. **Lack of reproducibility**: A developer using `latest` might start out with `v1` on their system. However, when they go to deploy on a different system, `latest` might pull a higher version with
The developer could use a KRM function to replace the tags, right ? (where you pass the resourceList of kind `kptfile` and mutate the image value)

2022-06-23 18:28 UTC, JonahSussman commented on enhancements/common/krm-function-manager.md
> +$ kaffine install alpha-foo-er
I was actually hoping to get feedback on the best way to approach this. I see two ways `Kaffine` could perform this action.

1. `Kaffine` will only manage references to the images. It passes along a YAML file to the function consumer where it handles downloading and installing the container.
2. `Kaffine` downloads and installs the container, perhaps even giving it some extra tagging information so it's local to the project. It passes along a YAML file with the local install of the container referenced.

Option 2 is significantly more complicated and obtrusive than 1. Additionally, if we're not careful, I could see how we'd end up with a `node_modules`-style bloat situation. Thus, for ease of "opting-in," I envision it working like option 1 for now.

2022-06-23 18:38 UTC, JonahSussman commented
@pranavgaikwad Thank you! With regards to your questions:

1. Crane, to my understanding, has a variety of OpenShift plugins that could be converted to KRM functions. This tool will be able to manage the versioning of each function used. Thus, the runner can focus on just running the functions. (Additionally, at some point in the future I envision being able to download and install entire pipelines with Kaffine, which will each require their own dependencies to manage)
2. I have not considered the possibility of proposing upstream. I would love to hear others' thoughts on this!

2022-06-23 18:48 UTC, JonahSussman commented on enhancements/common/krm-function-manager.md
> +1. **Lack of reproducibility**: A developer using `latest` might start out with `v1` on their system. However, when they go to deploy on a different system, `latest` might pull a higher version with
That could certainly be a possibility! I think the real power of a tool like this starts to show when you take into account the ease with which you can update functions. A single `update` command and Kaffine will handle the entire process of disovering updates and swapping the versioning for you.

2022-06-23 19:36 UTC, djzager reviewed
A few comments. Nice work by the way. I appreciate the detail.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +This enhancement proposes a new tool, called **Kaffine** to help manage the discovery, installation, removal, and updating of KRM functions. The tool acts as a buffer between the low-level management
Primarily though, `Kaffine` is concerned about discovery and updating right? I don't see a whole lot of need to install/remove containers (unless, as you said, we use binaries instead). So the biggest draw is the ability to know when new versions of a function are available...right?

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +<!-- - Actually installing or uninstalling containers -->
I agree that we probably shouldn't be installing/removing container images. Maybe `docker|podman pull` but removing them doesn't seem like something we want to start.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +Alice has in mind some functions that she wants to use that are created by Group Alpha. She adds the repo their repo via `kaffine config add repo group-alpha.example.com`. Then she searches which fun
This is the first I've seen the idea of a KRM Function repo defined. Am I missing it or do we need some exposition on what exactly I would find at `group-alpha.example.com`?

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +$ kaffine install alpha-foo-er
I wonder if it would make more sense if it was a declaration, I want to know about updates to `alpha-foo-er` function.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +$ kaffine update --check
Looks similar to `dnf update-check`, nice. So are the variations something like:

```
# Check for updates
kaffine update --check

# Update a single function
kaffine update alpha-foo-er

# Update all
kaffine update --all
```

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +Alice has in mind some functions that she wants to use that are created by Group Alpha. She adds the repo their repo via `kaffine config add repo group-alpha.example.com`. Then she searches which fun
Looks like it is later in the document, I think you should consider either:
1. Putting some of the technical description/notes before user stories so we have context when we get here.
2. Adding a glossary

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +Alice has in mind some functions that she wants to use that are created by Group Alpha. She adds the repo their repo via `kaffine config add repo group-alpha.example.com`. Then she searches which fun
Later, you describe the repos as having both a uri and a name...but here it is only the uri. Should it be `kaffine config add repo ${name} group-alpha.example.com`?

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +A repo has 2 main parts: a URI and a name. The URI is the location of the repo. It can be a server somewhere or a path on the local filesystem. The name is a user-friendly name of the repo. If two re
I think we should add repos the same way we add remotes with git...kaffine could force the names to be unique.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +$ kaffine list
Should `kaffine list` show what repo they come from? I'm not certain but figured I should ask.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +Searches all repositories for the function with the specified name. If no name is provided, it’s functionally the same as: `kaffine search '*' -r`. If output is piped, `-o yaml` is automatically sele
I personally would suggest we avoid detecting (and reacting to) whether `kaffine` is being piped. Users can add `-o yaml` themselves to pipe to follow-up commands.

2022-06-23 19:36 UTC, djzager commented on enhancements/common/krm-function-manager.md
> +A repo has 2 main parts: a URI and a name. The URI is the location of the repo. It can be a server somewhere or a path on the local filesystem. The name is a user-friendly name of the repo. If two re
I was hoping this portion would explain what the structure of a repo is but I'm not seeing it.

2022-06-23 23:10 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +This enhancement proposes a new tool, called **Kaffine** to help manage the discovery, installation, removal, and updating of KRM functions. The tool acts as a buffer between the low-level management
install is basically writing down the version and place for a KRM function, worth remembering that you can use KRM functions as binaries as well as containers.

2022-06-23 23:28 UTC, shawn-hurley requested changes
I think this enhancements motivation and user stories sections are really good and really tells us what/why and how for a user. I think we now have to get into the technical details and make a second specifically for this. We are very much on the right track but need to:
1. We need to see the links or mentions of the krm function catalog kep's.
2. We need to describe how the installation is saved on disk.
3. We need to describe how we save/know about a repo and what information is stored where.


I would also suggest that we consider what we **need** for the UX and what are nice to-haves and potentially move some of them to a follow-up. there are a lot of options for a lot of subcommands I am worried about the timing to complete all of this.

2022-06-23 23:28 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +Currently, when creating an application that utilizes KRM functions, there is no standardized way to manage the versioning these functions. While it is possible to manage the images of the functions
nit: the versioning of these functions.

2022-06-23 23:28 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +1. **Lack of reproducibility**: A developer using `latest` might start out with `v1` on their system. However, when they go to deploy on a different system, `latest` might pull a higher version with
I think it is worth noting that the goal is not to make a developer do things like replacing tags. we are making a porcelain command to make this easier and more ergonomic.

2022-06-23 23:28 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +1. **Dependant on container technology**: While KRM functions utilize container technology for now, if that requirement is ever relaxed to include raw binaries, relying on tags will simply not work.
raw binaries is a thing already IIUC.

2022-06-23 23:28 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +
Adding a third one, which is auditability. If this is defined in one place you don't accidentally use two different versions etc.

2022-06-23 23:28 UTC, shawn-hurley commented on enhancements/common/krm-function-manager.md
> +$ kaffine install alpha-foo-er
+1 @JonahSussman I agree on the use here of 1

+1 also on using make-believe stuff just to get the feel of the use by a user. 

I think for technical discussions, lets have that on that part of the enhancement.

2022-06-27 18:37 UTC, JonahSussman commented
@shawn-hurley @djzager I made some changes regarding the structure of how Kaffine gets its information. I agree that the concept of a "repo" was ill-defined and instead swapped it out with another technology proposed by [KEP-2906: Kustomize Function Catalog](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2906-kustomize-function-catalog). If you could review these changes and tell me what you think, I'd greatly appreciate it!

2023-02-17 18:25 UTC, jwmatthews commented
Due to the nature of Konveyor changing to align to the [Unified Vision](https://github.com/konveyor/enhancements/tree/master/enhancements/unified_experience), I think it's best we close this PR out.

If you feel strongly otherwise please reopen and add a comment.

2023-02-17 18:25 UTC, closed without merging