Progress reporting for trasnfer-pvc
konveyor/enhancements pull request #74
Opened 2022-07-11 16:56 UTC by pranavgaikwad

2022-07-11 17:38 UTC, djzager requested changes
A few nits. I really like this idea. There are several pieces that are not quite lining up for me...
1. We are parsing stderr/stdout, are we putting anything on stderr? This proposal talks about detecting stderr vs stdout but it's not clear if we are writing this stuff to disk somewhere or what.
2. Where are we saving the list of files that failed transfer? Stdout ... some file on disk, it isn't clear.
3. What happens to the original unprocessed logs? Saved to disk optionally, in the `kubectl logs` if the user really wanted them for debugging.

Clarity around :point_up: points would be really helpful.

2022-07-11 17:38 UTC, djzager commented on enhancements/crane-2.0/progress-reporting/README.md
> +> Optionally, write structured progress output to a file for automations to consume
I'm thinking these should be bullet points instead of quotes?

2022-07-11 17:38 UTC, djzager commented on enhancements/crane-2.0/progress-reporting/README.md
> +### User Stories [optional]
```suggestion
### User Stories
```

2022-07-11 17:38 UTC, djzager commented on enhancements/crane-2.0/progress-reporting/README.md
> +	}
Would we be writing anything to stderr?

2022-07-11 17:38 UTC, djzager commented on enhancements/crane-2.0/progress-reporting/README.md
> +This will allow us to generate progress information as and when logs are available on stream instead of processing all logs at a time. This improves performance, and reduces delay in progress updates
Do we intend to dump the raw logs somewhere?

2022-07-11 17:38 UTC, djzager commented on enhancements/crane-2.0/progress-reporting/README.md
> +As a user, I want to see a list of files that failed transfer so that I can use it to manually copy those files over.
I do not believe we currently have the idea of creating the tunnel for the user to aide them in such a manual transfer...should we?

2022-07-11 18:12 UTC, pranavgaikwad commented on enhancements/crane-2.0/progress-reporting/README.md
> +As a user, I want to see a list of files that failed transfer so that I can use it to manually copy those files over.
@djzager We currently don't. I dont know whether we should or not. Something to discuss.

2022-07-11 18:13 UTC, pranavgaikwad commented on enhancements/crane-2.0/progress-reporting/README.md
> +	}
@djzager thanks for pointing that out. Updated.

2022-07-11 18:19 UTC, pranavgaikwad commented
@djzager Updated document to answer your questions. By default, normal progress logs will be printed on stdout, errors on stderr. Errors will include actual error messages returned by rsync along with file names. If a file output is requested, both progress logs and errors will be written to a file in structured format (mostly JSON). I didn't consider the next steps (what to do with that output file) in the scope of this enhancement.

2022-07-11 18:23 UTC, jmontleon commented on enhancements/crane-2.0/progress-reporting/README.md
> +As a user, I want to see a list of files that failed transfer so that I can use it to manually copy those files over.
Maybe a debug mode where the client pod just sleeps so they can run commands manually and investigate issues on the server side to try and understand why it's falling apart, whether that be corruption, permissions, etc.

2022-07-11 18:25 UTC, jmontleon commented
Does this change anything about the way we do things in pipelines when running in cluster? I can't see why, but thought I'd ask.

2022-07-11 18:27 UTC, jmontleon commented
Any reason we should (or shouldn't) have a quiet or silent mode that only prints errors?

2022-07-12 13:57 UTC, djzager approved these changes
I like the idea of having a `--quiet` mode and structuring the output of failed files. Nice work.

2022-07-15 15:22 UTC, merged