Tackle Reporting Format
konveyor/enhancements pull request #83
Opened 2022-09-30 14:01 UTC by pranavgaikwad

2022-09-30 15:37 UTC, shawn-hurley reviewed
I do wonder if we need to discuss the input to analyzers. 

I think certain things, like AppID, etc., and any optional or changes to rules need to be communicated. 

I am missing the mapping, so it is hard to determine where each field is coming from and what that means for the feasibility of producing this output.

I would also like to consider making a schema for the Extras so that it can be verifiable and that a machine or UI can generate a friendly UI for the extra fields. 

I was also hopeful this would make filtering/searching based on these extras something that we can do.

2022-09-30 15:37 UTC, shawn-hurley commented on enhancements/tackle/addons-report-format/README.md
> +# Addons Report Format
I wonder if we need different types of add-ons. Each with their own defined API for the different phases of the modernization workflow?

2022-09-30 15:37 UTC, shawn-hurley commented on enhancements/tackle/addons-report-format/README.md
> +  - human readable
Can you explain what this means as a goal? is this an optional thing?

2022-09-30 15:37 UTC, shawn-hurley commented on enhancements/tackle/addons-report-format/README.md
> +type Category int
Are we going to define the list of Categories? Or they going to be registerable and more generic? 

If this is the case, I wonder if it should be a string,

2022-10-04 17:55 UTC, djzager commented on enhancements/tackle/addons-report-format/README.md
> +# Addons Report Format
I am in agreement with the idea that analyzers need their own defined API for input parameters and reporting results. While we don't yet have designs for having a defined API how an addon like tackle-test-generator would run, I see value in recognizing that not all addons are the same (require different inputs, have different format for outputs).

2022-10-04 18:36 UTC, djzager commented on enhancements/tackle/addons-report-format/README.md
> +type Violation struct {
I would think the more meaningful information we could associate with a report, the better -- key word being meaningful. Makes me think of the github action runs [like this one for example](https://github.com/migtools/crane/actions/runs/3061120534) that has a unique id but also lets you know the sha it was run against.

2022-10-05 14:41 UTC, shawn-hurley requested changes
Just some thoughts and comments on fields

One last thing that does not need to be added is how version negotiation is determined. is it sent as a header?

2022-10-05 14:41 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +Addons will be executed via Tackle Hub for source code analysis, binary analysis and more. The output of addons is crucial. It will be used by Tackle to take further actions such as creating project
nit: s/between addons/between analyzer addons/g

2022-10-05 14:41 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +The analyzer addons will follow a common format for their output. It can be represented as JSON or YAML. Tackle will expect some common fields from every addon. These fields will assist tackle create
I believe that we should consider removing the bit about open API until we decide where that open API should live, and we should make a full enhancement for it IMO.

2022-10-05 14:41 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
What happens if folks like t-shirt size pointing here like s,m,l.... etc. Do we believe that this is something to consider?

2022-10-05 14:41 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    Effort        string    `json:"effort,omitempty"`
Do we have a defined distinction between story points and effort?

2022-10-05 14:41 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    ExternalLinks []string  `json:"externalLinks"`
Would a helper text with an external link be a decent idea?

2022-10-06 18:07 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +    Effort        string    `json:"effort,omitempty"`
@shawn-hurley I took this field from windup report. I thought it was a text description of level of effort needed to mitigate the violation. But I was wrong. That field in windup report is actually just clone of StoryPoints field in text format. I am getting rid of that.

2022-10-06 18:42 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
just asking the question

2022-10-07 17:54 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
yeah maybe but I am wrong for worrying that an int is too restrictive, in that not every dev teams uses ints for estimating work

2022-10-07 18:39 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +Tackle will run different addons to perform different tasks in the modernization workflow. Analyzers are one example of addons that take a set of rules & source code as input, analyze the source code
```suggestion
Tackle will run different addons to perform different tasks in the modernization workflow. Analyzers are one example of addons that take a set of rules & source code as input, analyze the source code and return violations of those rules as output. The output is a violation report that helps Tackle take further actions. This document proposes a common format for the report of analyzer addons.
```

2022-10-07 18:39 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +    // AnalysisID id of the analysis that generated this output
It may make more sense for this not to be included as part of our output data format, instead being tracked by the hub itself. Or at least acknowledge that this information must come from the hub and can't be provided by an analyzer addon

2022-10-07 18:39 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
Would it make more sense to try and have effort level/complexity/etc provided as a few separate fields so that storypoints/tshirt sizing etc could be calculated later via user-configured formulae? At some point for these fields you have to provide some kind of concrete value or it's just not that useful, but maybe storypoints are too high-level/opinionated.

2022-10-07 18:39 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +    // Description text description about the incident
Comment says `Description`, field is called `Message`

2022-10-11 14:36 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +    // AnalysisID id of the analysis that generated this output
@fabianvf Analysis will happen within the addon. If you have multiple different analyses for the same codebase, how would you differentiate between the output for them? Did you mean the API URL will have it implicitely?

2022-10-12 17:18 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +    // AnalysisID id of the analysis that generated this output
yeah I was thinking the API url could have it implicitly, just because this is the only piece of data that can't come from inside an addon AFAIK. At least we should acknowledge that in the field description

2022-10-12 17:22 UTC, fabianvf commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
@pranavgaikwad the reason I think it could make sense to have multiple fields is that story points are usually derived from some combination of approximations of complexity, amount of work, and risk (ie chance that there is additional unknown work to be done post-change). Different teams will determine story points differently using one or more of those metrics, so there could be value in providing those knobs separately and allowing the architect/project manager/etc to determine how they want their story points to be calculated from those more fundamental values.

2022-10-12 17:36 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    StoryPoints   int       `json:"storyPoints,omitempty"`
Does this make life harder for the rule authors? Do we think (and I am inclined to lean this way) that a rule author knows the diff between complexity, amount of work, and risk?

2022-10-18 17:21 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +    // AnalysisID id of the analysis that generated this output
Seems like this would be the Task ID which is injected by the Hub into the addon (pod) at runtime and thus known to the addon. If we want to correlate Violations/Incidents by analysis, Seems best for the addon to be responsible for populating the entire report. The Hub API won't know the task ID to inject it.
That said, I would imagine that the AnalysisID is something that the addon (adapter) Go binding _could_ inject but it would just be a convenience.

2022-10-18 17:24 UTC, jortel commented
The reported data seems reasonable to me but I don't know much about the data or how it will be used.  I don't know the requirements.  But, seems fine from the hub perspective.

2022-10-20 10:14 UTC, jwmatthews commented on enhancements/tackle/analyzers-report-format/README.md
> +Tackle will run different addons to perform different tasks in the modernization workflow. Analyzers are one example of addons that take a set of rules & source code as input, analyze the source code
What do you think about updating this enhancement to refer to Konveyor instead of Tackle?

2022-10-20 13:16 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +    // AnalysisID id of the analysis that generated this output
I would love to have a discussion between UI/Core and us. And potentially even some UX designers if available.

My thought has been that multiple tasks could be executed for an application(s) at one time, all reporting back to be grouped for a given "analysis" run. 

This does seem to be a further thing that the hub and UI would need to know about, but wondering if we have thought about how many "analysis" addons can be tied together for a given point in time run and if this is valuable (I think it could be a good way to organize thoughts). 

The other point, is that eventually we will be making this call to the hub API, the thought right now is that we would report on the task level like `/analysis-addon-report/analysis-id/<id>` or something similar. 

I would like to consider this feature, but I assume this requires us to think about the UX past one analysis addon.

2022-10-26 14:41 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +Tackle will run different addons to perform different tasks in the modernization workflow. Analyzers are one example of addons that take a set of rules & source code as input, analyze the source code
Updated

2023-03-16 19:51 UTC, shawn-hurley requested changes
Where are we putting:

1. Rules that ran, but had no matches
2. Rules that had errors
3. the tags that a given ruleset sets? 

I think that we need to add these things to fully understand the apis and contracts that we need to build.

2023-03-16 19:51 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +Konveyor will run different addons to perform different tasks in the modernization workflow. Analyzers are one example of addons that take a set of rules & source code as input, analyze the source co
nit: source code -> source code or binaries?

2023-03-16 19:51 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
I thnk this should be on an incident, right?

2023-03-16 19:56 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
No since the incidents are just copies of the same Rule, we decided to keep it at Violation level. will update the comment

2023-03-16 22:21 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
@shawn-hurley lowest granularity for aggregation is at issue level. we do not envision breaking down the filters further

2023-03-17 12:42 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
@jortel @mansam I think I agree with Pranav, but want to double check :)

2023-03-17 14:51 UTC, pranavgaikwad commented
@shawn-hurley added new sections to talk about tags & errors, please take a look when you can

2023-03-17 15:39 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +### Output Format
Please consider the output of the analyzer CLI be a single report document that contains:
- violations
- dependencies
- tags

For example:
```
type Report struct {
    RuleSets []RuleSet
    Dependencies []Dep
    Tags []string
}
```

2023-03-17 15:40 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +	Links []Link `yaml:"links,omitempty"`
Incident.URL is just the URL but here we have a Link object that contains both a URL and a title. What is the value of the Title?
Would it be better to be more consistent with links?

2023-03-17 15:43 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +### Output Format
This could be a large amount of data is there a concern with this?

2023-03-17 15:53 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Links []Link `yaml:"links,omitempty"`
@jortel Incident has a file URI. On the other hand, Links contain an actual hyperlink and an additional title field for displaying in the report.

2023-03-17 16:29 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
I wonder if it would make sense to report effort on both:
Violation.Effort (sum of Incident.Effort)
Incident.Effort (effort for this incident).
Though I many misunderstand how effort is to be calculated.

2023-03-17 16:32 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +	Links []Link `yaml:"links,omitempty"`
Where does the Title come from?
How does the analyzer know how the UI wants to display it?

2023-03-17 17:03 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
> @jortel @mansam I think I agree with Pranav, but want to double check :)

Seems reasonable based on my current understanding.

2023-03-17 17:03 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Links []Link `yaml:"links,omitempty"`
@jortel Title comes from the Rule. Rule Authors provide them

2023-03-17 17:04 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
@jortel there's a 0 value for certain rules in windup. Some rules might not have the value specified, nil is for those cases

2023-03-17 20:01 UTC, djzager commented on enhancements/tackle/analyzers-report-format/README.md
> +- Propose data store to persist output
That part I'm missing is how the hub is going to consume this information. Maybe it's out of scope for the enhancement but we should probably mention that here.

Like, is the hub going to read it from the stdout of the pod, or is the addon going to hit some hub endpoint to report the results?

2023-03-17 20:32 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
understood.  but what is the meaningful difference?

2023-03-20 12:49 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
@jortel On the other hand, Tags are part of Violations right now. Tags are not necessarily "issues". We made effort a pointer to distinguish the 0 value. I think you bring up a good point here. It's best to move Tags out of violations and make Violations 1:1 with issues. That way, we don't have instances where we don't set effort at all. @shawn-hurley wdyt?

2023-03-20 12:50 UTC, pranavgaikwad commented on enhancements/tackle/analyzers-report-format/README.md
> +- Propose data store to persist output
@djzager out of scope for this one, will add as a non-goal

2023-03-20 12:55 UTC, shawn-hurley commented on enhancements/tackle/analyzers-report-format/README.md
> +	Effort *int `yaml:"effort,omitempty"`
There is a meaningful difference between a rule author not setting the effort when I think about the potential category. It is easier to disambiguate now than in the future on upgrade, and I believe it has minimal impact

2023-03-20 14:18 UTC, jortel commented on enhancements/tackle/analyzers-report-format/README.md
> +- Propose data store to persist output
The addon will POST the report to an endpoint (something like): /applications/1/analysis/report body=report.
The API is the integration point for everything. The addon uses the API to fetch whatever it needs from the inventory and uses the API to contribute back to the inventory.

2023-03-21 19:22 UTC, shawn-hurley approved these changes
For now the output being on a rule set and it being a list of rules sets makes sense to me. I am an plus one for now

2023-03-24 14:43 UTC, aufi approved these changes

2023-03-27 17:02 UTC, merged