Added an enhancement to enable Tackle to integrate with Jira
konveyor/enhancements pull request #85
Opened 2022-10-28 10:33 UTC by rromannissen

Signed-off-by: Ramon Roman Nissen <rromannissen@gmail.com>

2022-10-28 15:58 UTC, shawn-hurley requested changes
I have a few more questions

1. Is there a UX for someone not using the UI?
2. How does the hub talk to the integration code? Is this tree to the hub, or can the community contribute these out of tree?

2022-10-28 15:58 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +- This integration would enable Tackle to aggregate progress and status data about the overall migration initiative, opening the door for executive dashboards that could be consumed by a potential ne
nit: Tackle/Konveyor

2022-10-28 15:58 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +- Implement a Jira addon of any kind.
Can you expand on this non-goal? 

Are you saying this integration should not look like an add-on and should be its own thing or something else? 

Can you help me understand why not being an addon is important to you?

2022-10-28 15:58 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +A technical lead for the migration project that can create and modify applications and information related to it. The Architects don’t need to have access to sensitive information, but can consume it
Is there a security layer here that we need to make sure is covered? 

The use case is Architect A has access to applications 2 and 3 but not 3. They probably shouldn't be able to access the Jira instance for 3, right?

2022-10-28 15:58 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +![Jira Configuration - Create Instance](images/admin-jira-config-create.png?raw=true "Jira Configuration - Create Instance")
Nit: naming concern


Doesn't Jira call a running thing that you use an instance? could we re-name this to connection or something so that no one thinks we are spinning up a Jira Instance?

2022-10-28 15:58 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +### Test Plan
We have this as an open question I do think we should figure this out before merging.

we should also add to this, how does changes in the integration code when changed, also run through the hub and the hub should run the implementation when it changes. IMO.

2022-11-03 17:18 UTC, rromannissen commented on enhancements/tackle/tackle-jira-integration/README.md
> +- Implement a Jira addon of any kind.
Jira has its own type of addons. By this I don't mean not implementing whatever we need to build as a Konveyor addon (that needs to be determined by the engineers), but not building any kind of Atlassian Jira addon ([although the seem to have changed their name to apps](https://marketplace.atlassian.com/addons/app/jira)) to make Jira aware of this integration, at least for the moment. One of the things that we discussed back when this was on the drawing board was the possibility of having a Jira addon that would create projects for Konveyor migration with a given set of issue types, workflows and configuration. That was deemed as overkill on the very first iteration, but could be explored in the future. 

Nevertheless, good catch, we should update the terminology to reflect the new name.

2022-11-03 17:21 UTC, rromannissen commented on enhancements/tackle/tackle-jira-integration/README.md
> +A technical lead for the migration project that can create and modify applications and information related to it. The Architects don’t need to have access to sensitive information, but can consume it
Not really, the idea for this is to abstract Architects from using nominal Jira accounts. A service account is provided by the organization, and Architects can use it to access Jira indirectly. Regarding access to application 1 or 2 for an Architect, we don't have the concept of multi tenancy in Tackle. All architects are able to access all applications, so by extension it makes sense they are able to access their associated information in Jira as well, at least indirectly.

2022-11-03 17:22 UTC, rromannissen commented on enhancements/tackle/tackle-jira-integration/README.md
> +![Jira Configuration - Create Instance](images/admin-jira-config-create.png?raw=true "Jira Configuration - Create Instance")
Yeah, good catch. I'd say "Create Jira Instance Connection" could make more sense. How does that sound?

2022-11-03 17:24 UTC, rromannissen commented on enhancements/tackle/tackle-jira-integration/README.md
> +- This integration would enable Tackle to aggregate progress and status data about the overall migration initiative, opening the door for executive dashboards that could be consumed by a potential ne
I guess we should decide with @jwmatthews and @jortel if we want to get started replacing the terminology and refer to Tackle as Konveyor from now on.

2022-11-03 17:33 UTC, rromannissen commented on enhancements/tackle/tackle-jira-integration/README.md
> +- Implement a Jira addon of any kind.
I've changed it and added a link to the Jira App marketplace to make it self explanatory.

2022-11-03 17:50 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +A technical lead for the migration project that can create and modify applications and information related to it. The Architects don’t need to have access to sensitive information, but can consume it
Sounds good for now. I do think that this is a feature that we should add to the backlog then. 

I see it being useful for managed services as well as Active Directory integration.

2022-11-03 17:50 UTC, shawn-hurley commented on enhancements/tackle/tackle-jira-integration/README.md
> +![Jira Configuration - Create Instance](images/admin-jira-config-create.png?raw=true "Jira Configuration - Create Instance")
+1 was a small concern and it think that would solve it!

2022-11-03 17:56 UTC, shawn-hurley approved these changes
Changes sound good, the only concern is testing plan but once that has something I am good!

2022-11-03 20:12 UTC, jwmatthews commented on enhancements/tackle/tackle-jira-integration/README.md
> +- This integration would enable Tackle to aggregate progress and status data about the overall migration initiative, opening the door for executive dashboards that could be consumed by a potential ne
+1 to replace terminology.   I am trying to do this with how I speak/write but I still slip up :) 

In future we should consider if we want to go further and change repository names as well.

2022-11-03 20:42 UTC, jwmatthews commented
LGTM, I read what's captured so far and makes sense.

2022-12-14 13:40 UTC, rromannissen commented
@jortel @mansam  we have some new commits from atSistemas to review and discuss.

2022-12-15 14:43 UTC, rromannissen commented
@joseacr @tprumbs I think the best approach here would be for you to share details on how to interact with the different flavors and versions of the Jira API. Creating a standalone service would require additional resources for the deployment of Konveyor/Tackle, and the team is considering to include the integration with issue trackers as part of the core. Another interesting topic to contribute to would be to define automated testing strategies when dealing with Jira. We don't know of there is any kind of mock API or a way to spin up Jira instances on demand, but we definitely need something for our automated end to end tests.

2022-12-20 09:21 UTC, joseacr commented
> @joseacr @tprumbs I think the best approach here would be for you to share details on how to interact with the different flavors and versions of the Jira API. Creating a standalone service would require additional resources for the deployment of Konveyor/Tackle, and the team is considering to include the integration with issue trackers as part of the core. Another interesting topic to contribute to would be to define automated testing strategies when dealing with Jira. We don't know of there is any kind of mock API or a way to spin up Jira instances on demand, but we definitely need something for our automated end to end tests.

I completely agree @rromannissen. We will bring our functional knowledge about JIRA and its integrations.

2023-02-06 16:09 UTC, mansam approved these changes

2023-02-06 17:11 UTC, ibolton336 approved these changes

2023-05-30 19:03 UTC, merged